charts/internal/cloud-controller-manager/templates/cloud-controller-manager.yaml, pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
The OpenStack extension does now by default mount the host certificates from `/etc/ssl` and `/usr/share/ca-certificates` into the pods that are running in the seed and need to interact with the OpenStack API (kube-apiserver, kube-controller-manager (only until #1 is fixed), and cloud-controller-manager).
This is to accommodate OpenStack environments that are serving certificates signed by CAs not commonly known/trusted.
/cc @bnerd
```improvement operator
The OpenStack extension does now by default mount the host certificates from `/etc/ssl` and `/usr/share/ca-certificates` into the pods that are running in the seed and need to interact with the OpenStack API (kube-apiserver, …
```
=> Mount host certificate for KCM/CCM

Dockerfile, pkg/apis/openstack/validation/shoot.go, pkg/apis/openstack/validation/shoot_test.go
This PR enhances the shoot workers validation. It prevents that a worker `minimum` value can be set to 0 if `maximum > 0` since this is not yet supported by autoscaling, see https://github.com/gardener/gardener/pull/2045.
/cc @hardikdr
```improvement operator
The OpenStack shoot validator now checks that `workers[].minimum != 0` if `workers[].maximum >0` since autoscaling does not support this setup yet.
```
=> Validate min workers for autoscaling

charts/images.yaml
Add v1.18.0 cloud-controller-manager for 1.18 shoots.
Part of gardener/gardener#2095
```improvement operator
NONE
```
=> Add v1.18.0 cloud-controller-manager for 1.18 shoots

pkg/apis/openstack/validation/shoot.go, pkg/apis/openstack/validation/shoot_test.go, pkg/validator/shoot_handler.go
Allow defining zones multiple times for workers.
Ready for review but please don't merge yet. I want to do some final tests.
```improvement operator
The OpenStack validator now allows zones to be specified multiple times for a worker group.
```
=> Allow defining zones multiple times for workers

Dockerfile, docs/usage-as-operator.md, go.mod, pkg/apis/openstack/validation/controlplane.go, pkg/apis/openstack/validation/controlplane_test.go, pkg/apis/openstack/validation/infrastructure.go, pkg/apis/openstack/validation/infrastructure_test.go, pkg/utils/utils.go, pkg/utils/utils_suite_test.go, pkg/utils/utils_test.go, pkg/validator/shoot_validator.go, vendor/modules.txt
This PR adds the support for wildcard expressions when declaring `floatingPools[].name` in the `CloudProfile`.
Fixes #62
`LoadBalancerClasses` in the `ControlPlaneConfig` are now cross checked against the configured `FloatingPoolName` in the `InfrastructureConfig`.
```improvement operator
It is now possible to use simple wildcard expressions when configuring `floatingPools[].name` in the `CloudProfileConfig`. As a consequence, the `FloatingPoolName` in a shoot cluster is matched against this wildcard expression instead of only allowing a strict match. Please consult the documentation https://github.com/gardener/gardener-extension-provider-openstack/blob/c0588dd37 …
```
=> Allow wildcard expressions in FloatingPoolNames

charts/internal/cloud-provider-config/templates/cloud-provider-config-global.tpl, charts/internal/cloud-provider-config/values.yaml, docs/usage-as-operator.md
As of https://github.com/kubernetes/cloud-provider-openstack/pull/977 (released with v1.18.0 version of CCM) the `UseOctavia` is defaulted to `true`. Hence, let's explicitly set it to `false` so that our old behaviour is kept.
/cc @kayrus 
```improvement operator
The `useOctavia` setting of the cloud-controller-manager is now explicitly set to `false`. You can set it to `true` using the `ControlPlaneConfig`.
```
=> Explicitly set 'useOctavia' to 'false'

pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
Co-authored-by: Uwe Krueger <uwe.krueger@sap.com>
If multiple load balancer classes are defined in a floating pool of the cloud profile constraints, currently the default class must be named "default". If no "default" LB class is provided, the Openstack CCM chooses one by random. With this PR the first load balancer class is used instead.
Additionally it is ensured that the floating network ID from the infrastructure is used for all LB classes.
Fixes #
```improvement operator
If a floating pool in the cloud profile defines no load balancer class named "default", the first one is used as default.
```
=> use first load balancer class as default if no class with name "default" provided

pkg/controller/infrastructure/actuator_reconcile.go
With this PR we will no longer requeue with the constant `30s` on errors but leverage the exponential backoff functionality of the underlying workqueue.
Part of gardener/gardener#2253
```improvement operator
NONE
```
=> Use workqueue backoff

charts/gardener-extension-validator-openstack/charts/application/templates/rbac.yaml, docs/usage-as-operator.md, hack/api-reference/api.md, pkg/apis/openstack/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/zz_generated.conversion.go, pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go, pkg/apis/openstack/validation/cloudprofile.go, pkg/apis/openstack/validation/cloudprofile_test.go, pkg/apis/openstack/validation/controlplane.go, pkg/apis/openstack/validation/controlplane_test.go, pkg/apis/openstack/validation/infrastructure.go, pkg/apis/openstack/validation/infrastructure_test.go, pkg/apis/openstack/zz_generated.deepcopy.go, pkg/internal/credentials.go, pkg/validator/shoot_handler.go, pkg/validator/shoot_validator.go
Add an optional domain field to FloatingPool to allow configuring that the given floating pool is only available in the specified domain.
The cloud profile validation now checks the specified floatingpools for consistent combinations of name/region/domain.
The shoot validation prevents using floating pools from a different region/domain combination.
Example:
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: CloudProfile
metadata:
name: openstack
spec:
type: openstack
...
providerConfig:
apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
kind: CloudProfileConfig
...
constraints:
floatingPools:
- name: fp-pool-1 #valid in `domain1` domain in `eu-1` region
region: eu-1
domain: domain1
- name: fp-pool-2 # valid in all domains in …
```
=> add domain field to floatingpool and validate it

cmd/gardener-extension-provider-openstack/app/app.go, go.mod, go.sum, vendor/github.com/gardener/gardener/extensions/pkg/controller/backupentry/reconciler.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/controller.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator.go, vendor/github.com/gardener/gardener/pkg/scheduler/controller/shoot/scheduler_control.go, vendor/modules.txt
Vendor gardener/gardener@4f4a1db77d90a828d5681ee4a7daab9a920ed3af
```improvement operator
`ClusterRole`s for the machine-controller-manager that might be orphaned now as they created with an earlier, buggy version of this controller are now cleaned up during startup.
```
=> Vendor gardener/gardener@28def0ceecf15f5c7323cd5e65300adc0b0c81da

pkg/controller/controlplane/valuesprovider.go, pkg/controller/worker/machines.go, pkg/internal/infrastructure/infrastructure.go, pkg/internal/infrastructure/terraform.go, pkg/internal/infrastructure/terraform_test.go, pkg/internal/terraform.go, pkg/internal/terraform_test.go, pkg/openstack/client/swift.go, pkg/openstack/credentials.go, pkg/validator/shoot_handler.go, pkg/validator/shoot_validator.go
/area quality
/kind bug
This PR fixes a bug that caused the validator-openstack to crash because it was depending on the `charts` directory. However, the `charts` directory is only present in the `provider-openstack`.
```improvement operator
A bug has been fixed that caused the `validator-openstack` to crash due to an invalid dependency on the OpenStack's `charts/images.yaml` file.
```
=> Move credentials methods from pkg/internal to pkg/openstack

charts/internal/cloud-provider-config/templates/_cloud-provider-config-global.tpl, charts/internal/cloud-provider-config/values.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
With this PR we add the region information to the cloud-provider config. This is required to enable the OpenStack cloud controllers to detect the correct Keystone endpoint in case the OpenStack environment has multiple regions.
/cc @timuthy @vasu1124 
```noteworthy operator
The OpenStack cloud controllers are now correctly bootstrapping and behaving in case the underlying OpenStack environment supports multiple regions.
```
=> Add region information to cloud-provider config

go.mod, go.sum, pkg/controller/infrastructure/actuator_delete.go, vendor/github.com/gardener/gardener/extensions/pkg/terraformer/config.go, vendor/github.com/gardener/gardener/extensions/pkg/terraformer/state.go, vendor/github.com/gardener/gardener/extensions/pkg/terraformer/types.go, vendor/github.com/gardener/gardener/extensions/pkg/terraformer/waiter.go, vendor/github.com/gardener/gardener/pkg/apis/core/v1alpha1/defaults.go, vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/defaults.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/health_check.go, vendor/modules.txt
/area quality
/kind bug
With this PR, the infrastructure actuator waits for all terraformer pods from previous reconciliations to be deleted before checking the state cm for an empty state.
This is to ensure, that a terraformer pod, which creates the infrastructure for a freshly created cluster, is deleted / has finished, so we don't falsely exit early because the state configmap is still empty (and therefore don't delete the infrastructure at all).
Ref https://github.com/gardener/gardener-extension-provider-aws/issues/121
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull …
=> Wait for terraformer before deleting infrastructure

pkg/controller/controlplane/valuesprovider.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/area quality
After https://github.com/gardener/gardener-extension-provider-openstack/commit/3bf9f686ea6838aef2d87cbe1ff75f459037594b (introduced in #65) the `StorageClass`es cannot be applied for existing clusters anymore. The reason is that we had removed the `availability` parameter, however, `StorageClass`es are immutable.
This PR deletes such old existing `StorageClass`es to allow them being recreated with the correct specification. It is done as part of the `Worker` controller because the shoot's kube-apiserver might not be up and running in the `ControlPlane` reconciliation.
/cc @RaphaelVogel @mvladev  …
=> Workaround storage class changes

README.md
Removed testgrid links to outdated versions and added a disclaimer
/area Documentation
Fixes #
```improvement operator
NONE
```
=> Remove testgrid links to tests with kubernetes version < 1.15

charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml
/kind bug
Removes the `NoExecute` toleration from components running in the Seed cluster, such as the CCM. This toleration should not be needed for such components, see the discussion in https://github.com/gardener/gardener-extension-provider-azure/pull/120.
```improvement operator
NONE
```
=> Remove NoExecute toleration from CCM

README.md, example/20-crd-controlplane.yaml
I started a new setup on kind and applied the CRDs under example, but `make start` complained `"no matches for kind \"ControlPlane\" in version \"extensions.gardener.cloud/v1alpha1\"`.
```improvement operator
NONE
```
=> Nit: Add missing CRD under example/

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/kind bug
The `StorageClass` cleanup is now skipped for hibernated shoots.
Thanks to @mandelsoft @timuthy for reporting!
```improvement user
An issue has been fixed that prevented the `Worker` reconciliation from succeeding for hibernated shoots.
```
=> Skip `StorageClass` cleanup for hibernated shoots

charts/gardener-extension-validator-openstack/charts/runtime/templates/poddisruptionbudget.yaml
/area high-availability robustness
This PR adds a `PodDisruptionBudget` to the validator chart which will be created when the replica count is larger than `1`, similar to how it's done for the extension controller.
/invite @ialidzhikov @timuthy 
```improvement operator
A `PodDisruptionBudget` for the validation server is now automatically deployed as part of its Helm chart if the replica count is larger than `1`.
```
=> Add PDB for validation server

README.md, charts/images.yaml, charts/internal/cloud-provider-config/templates/cloud-provider-disk-config.yaml, charts/internal/cloud-provider-config/values.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-attacher.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-provisioner.yaml, docs/usage-as-operator.md, hack/api-reference/api.md, pkg/apis/openstack/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/zz_generated.conversion.go, pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go, pkg/apis/openstack/zz_generated.deepcopy.go, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
/area open-source usability
/platform aws
This PR adds support for 1.19 to the extension.
CSI will be used for 1.19 shoots. Older shoots will keep using the in-tree legacy volume provisioners.
Part of gardener/gardener#2629
* I have successfully validated the functionality as follows:
* :white_check_mark: Create new clusters with versions < 1.19
* :white_check_mark: Create new clusters with version  = 1.19
* :white_check_mark: Upgrade old clusters from version 1.18 to version 1.19
* :white_check_mark: Delete clusters with versions < 1.19
* :white_check_mark: Delete clusters with version  = 1.19 …
=> Support for Kubernetes 1.19

charts/internal/shoot-storageclasses/templates/storageclasses.yaml
/area storage
/kind task
I was assuming that all CSI StorageClasses are configured with .volumeBindingMode=WaitForFirstConsumer but that is not the case for the cinder ones.
Part of https://github.com/gardener/gardener-extension-provider-openstack/pull/137/files
```improvement user
The CSI StorageClasses (with provisioner `cinder.csi.openstack.org`) do now also specify `WaitForFirstConsumer` for volumeBindingMode.
```
=> Use WaitForFirstConsumer also for CSI StorageClasses

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml
/area storage
/kind bug
Currently for v1.19 the guestbook test is failing with:
```
$ k -n gardener-e2e-v2xt6 get po
NAME             READY   STATUS             RESTARTS   AGE
redis-master-0   0/1     CrashLoopBackOff   5          4m13s
$ k -n gardener-e2e-v2xt6 logs redis-master-0
06:57:52.24 INFO  ==> ** Starting Redis **
1:C 11 Sep 2020 06:57:52.256 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 11 Sep 2020 06:57:52.256 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 11 Sep 2020 06:57:52.256 # Configuration loaded
1:M 11 Sep 2020 06:57:52.257 # Can't open the append-only file: Permission denied
```
Investigation shows that the fsType is …
=> Fix volume fsType handling for CSI volumes

charts/internal/shoot-system-components/charts/csi-driver-node/templates/podsecuritypolicy.yaml
/area storage
/kind bug
With Shoot that specifies`.spec.kubernetes.allowPrivilegedContainers=false`:
```
$ k -n kube-system describe ds csi-driver-node
Events:
Type     Reason            Age                From                  Message
----     ------            ----               ----                  -------
Warning  FailedCreate      22m (x8 over 23m)  daemonset-controller  Error creating: pods "csi-driver-node-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.containers[0].securityContext.capabilities.add: Invalid value: "SYS_ADMIN": capability may not be added spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used …
```
=> Adapt csi-driver-node PSP

charts/internal/cloud-provider-config/templates/cloud-provider-disk-config-csi.yaml, charts/internal/cloud-provider-config/templates/cloud-provider-disk-config.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go, pkg/openstack/types.go, pkg/webhook/controlplane/ensurer.go
/area storage
/kind bug
Currently the csi-driver-controller and kube-controller-manager are mounting the Secret `cloud-provider-disk-config`. 
Recently this Secret was updated with CSI specific configuration (`[BlockStorage]`). This configuration is unknown to kube-controller-manager and it panics with:
```
F0913 10:57:56.155544       1 controllermanager.go:244] error building controller context: cloud provider could not be initialized: could not init cloud provider "openstack": warning:
can't store data at section "BlockStorage", variable "rescan-on-resize"
```
This PR reverts the kube-controller-manager Secret and creates a new Secret that is used by the csi-driver-controller. …
=> Use separate Secret for csi-driver-controller

pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
/kind cleanup
Clean up the deletion of legacy cloud provider ConfigMaps. 
```improvement operator
NONE
```
=> Clean up the deletion of legacy cloud provider ConfigMaps

README.md, docs/compatibility.md, pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/kind bug
Previous openstack versions  ensure a volume mount on the shoot kube-apiserver with name `usr-share-ca-certificates` with path `/usr/share/ca-certificates for Shoots that does not use CSI or is not yet migrated. 
However Gardener version > 1.10.0 always adds a volume mount for Shoots with Kubernetes version > 1.17 with name `usr-share-cacerts` also with path `/usr/share/ca-certificates`.
This is problematic for Shoots where the provider ensures the `usr-share-ca-certificates` path
- All existing & new Kubernetes versions 1.17.x  & 1.18.x 
- 1.19.x that are not migrated yet to CSI. 
The existing volume mount `usr-share-ca-certificates` needs to be …
=> Ensure that shoot kube-apiserver has no incompatible mount of usr/share/ca-certificates

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml
Fixes #157 
```improvement operator
CSI sidecar containers timeout is now increased to `3m`.
```
cc @rfranzke
=> Set CSI controller sidecar containers timeout

charts/internal/cloud-provider-config/templates/cloud-provider-disk-config-csi.yaml, charts/internal/cloud-provider-config/values.yaml, docs/usage-as-operator.md, hack/api-reference/api.md, pkg/apis/openstack/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/zz_generated.conversion.go, pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go, pkg/apis/openstack/zz_generated.deepcopy.go, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
/area storage
The introduced flag tells the CSI-Driver, that there is a upper limit for mounted volumes on a node. 
```improvement operator
Added possibility to set nodeVolumeAttachLimit within the cloud profile.
```
=> added nodeVolumeAttachLimit

charts/internal/openstack-infra/templates/main.tf, charts/internal/openstack-infra/values.yaml, docs/usage-as-operator.md, hack/api-reference/api.md, pkg/apis/openstack/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/zz_generated.conversion.go, pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go, pkg/apis/openstack/zz_generated.deepcopy.go, pkg/internal/infrastructure/terraform.go, pkg/internal/infrastructure/terraform_test.go
This PR adds a new option `useSNAT` to the provider's specific `CloudProfileConfig`. If set to `true`, Gardener creates the OpenStack Router with the [enable_snat](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/networking_router_v2#enable_snat) option.
Fixes parts of #122
/cc @schrodit @vasu1124 @vlerenc @markbgrdt
```improvement operator
The OpenStack extension now created OpenStack routers with [enable_snat](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources …
```
=> Add useSNAT option to CloudProfile

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/area storage
/kind cleanup
Clean up the workaround introduced with https://github.com/gardener/gardener-extension-provider-openstack/pull/102.
I believe we no longer need it as StorageClass should be already adapted by the temporary workaround logic. We also introduced https://github.com/gardener/gardener-extension-provider-openstack/pull/130 which should re-create the StorageClasses on invalid updates.
```improvement operator
NONE
```
=> Clean up StorageClass update workaround

.test-defs/provider-openstack.yaml, test/tm/generator.go
How to categorize this PR?
What this PR does / why we need it:
This PR adds all properties to the "provider-openstack" test definition. In addition to this, as discussed in [PR:191,](https://github.com/gardener/gardener-extension-provider-aws/pull/191) the default parameters handling is changed.
This way one test definition will be used by the integration tests where shoots with different networks from the defaults must be created (e.g. for registering a new seed for the control plane migration) and it will preserve the default behaviour for other integration tests (e.g. for shoot creation) that relies on the default values.
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:
Release note:
```
NONE
```
=> Changing the default parameters handling and adding all properties to the test definition

charts/internal/machine-controller-manager/seed/templates/deployment.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml, test/e2e/netpol-gen/app/openstack.go, test/e2e/networkpolicies/networkpolicy_test.go
/kind cleanup
Fore more details see https://github.com/gardener/gardener-extension-provider-aws/pull/230
```improvement operator
NONE
```
=> Remove deprecated role label key from components

charts/images.yaml, pkg/internal/terraform.go
/area quality robustness
This PR let the infrastructure actuator use the terraformer v2.
```noteworthy operator
The terraformer version has been upgraded to version `v2.0.0`.
```
/invite @timebertt 
/invite @kon-angelo
=> Terraformer v2

charts/images.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml
/area storage
```dependency user
The following images are updated:
- docker.io/k8scloudprovider/cinder-csi-plugin: v1.18.0 -> v1.19.0
- k8s.gcr.io/sig-storage/csi-provisioner: v2.0.0 -> v2.0.4
- k8s.gcr.io/sig-storage/csi-attacher: v3.0.0 -> v3.0.2
- k8s.gcr.io/sig-storage/csi-node-driver-registrar: v2.0.0 -> v2.0.1
```
=> Update CSI driver and sidecar images

charts/images.yaml
/kind bug
Similarly to https://github.com/gardener/gardener-extension-provider-alicloud/issues/208, currently provider-openstack will deploy occm@v1.17 even for Kubernetes >= 1.18.
https://github.com/gardener/gardener-extension-provider-openstack/blob/97f277aca370214636f21a41ee4624262a5f69d3/charts/images.yaml#L11-L20
Currently for a v1.19 cluster, the deployed occm version is v1.17.0:
```
$ k -n shoot--foo--bar get po cloud-controller-manager-b5f86b65f-5lzcr -o yaml | grep image
image: k8scloudprovider/openstack-cloud-controller-manager:v1.17.0
```
```bugfix operator
An issue causing provider-openstack to deploy wrong version of the cloud-controller-manager for Kubernetes >= 1.18 clusters is now fixed.
```
=> Fix occm version for Kubernetes >= 1.18

pkg/controller/worker/actuator.go, pkg/openstack/client/client.go, pkg/openstack/client/swift.go
/kind bug
Fixes #
```bugfix operator
Fix a bug, where a missing "auth_url" field from the credentials secret would block the creation of a shoot. In case this field is now missing from the provided credentials, the auth_url is taken from the `CloudProfile` used instead.
```
=> get missing auth_aul from cloudprofile

pkg/controller/worker/actuator.go, pkg/openstack/client/client.go, pkg/openstack/client/swift.go
/kind bug
Fixes #
```bugfix operator
Fix a bug, where a missing "auth_url" field from the credentials secret would block the creation of a shoot. In case this field is now missing from the provided credentials, the auth_url is taken from the `CloudProfile` used instead.
```
=> [release-v1.14] get missing auth_aul from cloudprofile

charts/images.yaml
Fixes #148
```other operator
provider-openstack is now using openstack cloud-controller-manager@v1.19 for Kubernetes >= 1.19 clusters.
```
=> Use occm@v1.19 for Kubernetes >= 1.19

pkg/apis/openstack/validation/controlplane.go, pkg/apis/openstack/validation/controlplane_test.go, pkg/apis/openstack/validation/infrastructure.go, pkg/apis/openstack/validation/infrastructure_test.go, pkg/validator/serialization.go, pkg/validator/shoot_validator.go
Now we only validate the `.spec.provider.{infrastructure,controlPlane}Config` values against the constraints defined in the `CloudProfile` if the values in the shoot were changed during an update. This is to ensure that constraints can be removed from the `CloudProfile` without breaking updates to `Shoot` resources.
```bugfix operator
The validator does now only validate the `.spec.provider.{infrastructure,controlPlane}Config` values of a `Shoot` against the constraints in the `CloudProfile` if the values were changed during a `Shoot` update.
```
=> Only validate infra/controlPlane config against CloudProfile on change

charts/images.yaml
/area storage
```other user
provider-openstack is now using cinder-csi-plugin@v1.20 for Kubernetes >= 1.20 clusters.
```
=> Use cinder-csi-plugin@v1.20.0 for Kubernetes >= 1.20

pkg/cmd/options.go, pkg/webhook/cloudprovider/add.go, pkg/webhook/cloudprovider/ensurer.go, pkg/webhook/cloudprovider/ensurer_test.go, vendor/github.com/gardener/gardener/extensions/pkg/webhook/cloudprovider/cloudprovider.go, vendor/github.com/gardener/gardener/extensions/pkg/webhook/cloudprovider/mutator.go, vendor/modules.txt
Implements a webhook that will add the `auth_url` field found in the `cloudprofile` to the `cloudprovider` secret. 
`auth_url` is necessary to initiate a client for the provider API but `auth_url` - currently - can exists in two places:
+ in the cloudprofile.
+ in the cloudprovider secret.
The problem that we try to solve with this PR are:
a) we want the MCM's `machineclasses` to use directly the cloudprovider secret. Since `auth_url` could be missing and MCM does not have access to the cloudprofile, the change wouldn't work.
b) prepare for issue #197, without breaking backwards compatibility with MCM's `OpenstackMachineClass`. With this change …
=> Add cloudprovider webhook to add auth_url from cloudprofile

charts/images.yaml
Fixes #148
```other operator
provider-openstack is now using openstack cloud-controller-manager@v1.20 for Kubernetes >= 1.20 clusters.
```
=> Use occm@v1.20 for Kubernetes >= 1.20

docs/usage-as-end-user.md, pkg/apis/openstack/validation/shoot.go, pkg/apis/openstack/validation/shoot_test.go
This PR removes the validation checks that prevented worker groups to change server group settings after their creation. This will trigger a rolling update (by changing the `MachineClass` hash)
Fixes #
```doc user
Allow updating server group settings on existing worker groups.
```
=> remove server group update validation

pkg/webhook/cloudprovider/ensurer.go, pkg/webhook/cloudprovider/ensurer_test.go
/kind bug
Fixes a bug where the auth-url webhook was updating the secret using the wrong key for the data.
Fixes #
```other operator
```
=> fix secret key

charts/images.yaml
/kind bug
After https://github.com/gardener/gardener-extension-provider-openstack/pull/205 the ControlPlane reconciliation for K8s < 1.19 fails with:
```
lastErrors:
- description: >-
task "Waiting until shoot control plane has been reconciled" failed:
Error while waiting for ControlPlane shoot--foo--bar/bar
to become ready: extension encountered error during reconciliation:
Error reconciling controlplane: could not apply control plane chart for
controlplane 'shoot--foo--bar/bar': could not inject
chart 'csi-driver-controller' images: could not find image
"csi-driver-cinder" opts runtime version v1.18.14 target version 1.18.14
taskID: Waiting until shoot control plane has been reconciled
```
Although the csi-driver is deployed only for K8s > 1.19, the `csi-driver-cinder` image is part of …
=> Fix ControlPlane reconciliation for K8s < 1.19

charts/internal/machineclass/templates/machineclass.yaml, charts/internal/machineclass/values.yaml, pkg/controller/worker/machine_controller_manager.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go, pkg/openstack/types.go, pkg/webhook/cloudprovider/ensurer.go
Uses the machine classes .{spec.}credentialsSecretRef field. It is a reference to a secret containing only the credentials, while today's `.spec.secretRef` still contains the user-data. [See here for more details](https://github.com/gardener/machine-controller-manager/pull/578).
Uses the worker's secret reference as the credentialsSecretRef.
This means all worker pools use the same "cloudprovider" secret containing only the cloud provider credentials.
The existing MachineClass SecretReference then only contains the user data that is different for each pool.
Fixes #
Set to …
=> update machineclasses to use cloudprovider secret

charts/gardener-extension-validator-openstack/charts/runtime/templates/vpa.yaml, charts/gardener-extension-validator-openstack/values.yaml
/area scalability auto-scaling
VPA for validator/admission component
```noteworthy operator
The validator/admission component's Helm chart is now deploying a `VerticalPodAutoscaler` resource by default. If undesired or no VPA is available in the garden cluster then it can be turned of via `.Values.global.vpa.enabled=false`.
```
=> VPA for validator/admission component

charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
/kind bug
When the `cloud-provider-config` for the CSI disk plugin changes then it needs to be restarted so that it can reload the changed config. This PR adds the missing checksum annotation to trigger the restart on config change.
/cc @vlerenc 
```bugfix user
An issue has been resolved which prevented the CSI driver from properly functioning when the infrastructure credentials were changed.
```
=> Secret data checksum for CSI driver on worker nodes

charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
Add the Openstack domain name, the tenant/project name and the Shoot technical name (Project name + Shoot name) as http headers for the API calls which the the Openstack Cloud Controller Manager and CSI drive run against OpenStack APIs.
This should help to detect log messages which belong to certain Shoot faster on the Openstack provider side.
Fixes #214
I wanted to play around before I remove the draft state.
```other operator
The name of the Openstack domain, tenant/project name and the technical name of the respective Shoot will be added as http …
```
=> Add useragent header for api call issued by ccm and csi driver

charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
/kind bug
Cherry pick of #226 on release-v1.16.
#226: Secret data checksum for CSI driver on worker nodes
```bugfix user
An issue has been resolved which prevented the CSI driver from properly functioning when the infrastructure credentials were changed.
```
=> [release-v1.16] Secret data checksum for CSI driver on worker nodes

charts/images.yaml
/kind bug
Cherry pick of #227 on release-v1.16.
#227: [ci:component:github.com/gardener/terraformer:v2.1.0->v2.1.1]
**Release Notes*:
``` bugfix operator github.com/gardener/terraformer #72 @timebertt
A bug was fixed that caused terraform to leak its finalizer on ConfigMaps and Secrets in case of an interrupt during `terraform destroy`.
```
=> [release-v1.16] [ci:component:github.com/gardener/terraformer:v2.1.0->v2.1.1]

charts/internal/openstack-infra/templates/main.tf, charts/internal/openstack-infra/values.yaml
Add max retries for api call to retry failed or throttled operations.
Fixes partly #220
Require `terraformer-openstack` with provider openstack `v.1.37.0` integrated. See https://github.com/gardener/terraformer/pull/68
```NONE
```
/invite @kon-angelo 
cc @kayrus
=> Add max retries to repeat failed or throttled operations

charts/images.yaml, charts/internal/machine-controller-manager/seed/templates/deployment.yaml, charts/internal/machine-controller-manager/seed/values.yaml, charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml, charts/internal/machineclass/templates/machineclass.yaml, pkg/controller/worker/machine_controller_manager.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go, pkg/openstack/types.go
/kind api-change
Changes the MCM deployment to the OOT repo one. Also adapts the `MachineClass` templates for the new CR.
Fixes #
Drafted until first release of the OOT repo. 
```other operator
Openstack extension now uses the new Out-Of-Tree MCM implementation.
```
=> adapt to OOT MCM

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml
`csi-driver-controller` Deployment is now annotated with the controlplane labels to allow the `dependency-watchdog` to restart the csi-driver-controller when the apiserver recovers.
Ref https://github.com/gardener/gardener/blob/v1.18.0/docs/usage/seed_bootstrapping.md#endpoint
```other operator
NONE
```
=> Add controlplane label to csi-driver-controller

charts/internal/openstack-infra/templates/main.tf, charts/internal/openstack-infra/templates/variables.tf, charts/internal/openstack-infra/values.yaml, pkg/controller/infrastructure/actuator_reconcile.go, pkg/internal/infrastructure/terraform.go, pkg/internal/infrastructure/terraform_test.go, pkg/internal/terraform.go, pkg/internal/terraform_test.go
Instead of templating the credentials (`domainName`, `tenantName`) into the Terraform script we are now using container environment variables with references to the `cloudprovider` secret (similar to how it's done for `username` and `password`).
The Terraform script is only updated on creation/reconciliation, but if an `Infrastructure` is already marked for deletion then it's never updated again. This is a problem if the `domainName` or `tenantName` changes.
/cc @dguendisch @timuthy 
```other operator
NONE
```
=> Use Terraform variables for credentials

charts/internal/openstack-infra/templates/main.tf
Add ingress rule to allow `UDP`.
This is required for using UDP LB on `openstack`.
```other operator
Add ingress rule to allow `UDP`. 
```
=> Add security rule for udp

pkg/apis/openstack/validation/shoot.go, pkg/apis/openstack/validation/shoot_test.go, pkg/openstack/client/client.go, pkg/openstack/client/compute.go
/kind bug
/priority blocker
This PR fixes an issue when to trying to create servergroups with nova API `>= 2.64`. The request no longer accepts the `Policies` field on those versions. The current client picked the highest supported version of the Nova API and if that was greater than `2.64` the creation of servergroups would fail.
Instead, do not set the microversion of the client.  In case `soft-*` servergroup policies are requested, pin the client to `2.15`, since its the minimum version that supports these values.
Fixes #
```bugfix operator
Fix a bug in servergroup creation when the Nova …
```
=> fix failing servergroup creation on Nova 2.64+

charts/gardener-extension-validator-openstack/charts/application/templates/validatingwebhook-validator.yaml, example/40-validatingwebhookconfiguration.yaml
Set the timeout for the webhook to 10 seconds
Fixes #
```other operator
The timeout seconds for the validating admission webhook is now set to 10s.
```
=> Set the timeout for the webhook to 10 seconds

charts/images.yaml
/kind bug
Cherry pick of #256 on release-v1.17.
#256: Update kubernetes-csi/livenessprobe
```bugfix user
The following image is updated (see [CHANGELOG](https://github.com/kubernetes-csi/livenessprobe/blob/v2.2.0/CHANGELOG/CHANGELOG-2.2.md) for more details):
- k8s.gcr.io/sig-storage/livenessprobe: v2.1.0 -> v2.2.0
```
=> [release-v1.17] Automated cherry pick of #256: Update kubernetes-csi/livenessprobe

charts/images.yaml
Use openstack cloud-controller-manager `v1.21.0` and cinder csi `v1.21.0` for kubernetes clusters `>= v1.21`.
Draft as currently running tests.
Required for #248
```other operator
Openstack Kubernetes cluster `>= v1.21` use now the Openstack cloud-controller-manager `v1.21` and cinder csi `v1.21`.
```
=> Use occm@v1.21.0 and cinder csi@v1.21.0 for k8s >= v1.21

pkg/openstack/credentials.go
/kind bug
Do not print secret content in error message
Fixes #
```bugfix operator
No longer print secret data into error messages.
```
=> Do not print secret content in error message

pkg/openstack/credentials.go
Cherry pick of #274 on release-v1.17.
#274: Do not print secret content in error message
```bugfix operator
No longer print secret data into error messages.
```
=> [release-v1.17] Automated cherry pick of #274: Do not print secret content in error message

pkg/openstack/credentials.go
Cherry pick of #274 on release-v1.16.
#274: Do not print secret content in error message
```bugfix operator
No longer print secret data into error messages.
```
=> [release-v1.16] Automated cherry pick of #274: Do not print secret content in error message

pkg/openstack/credentials.go
Cherry pick of #274 on release-v1.18.
#274: Do not print secret content in error message
```bugfix operator
No longer print secret data into error messages.
```
=> [release-v1.18] Automated cherry pick of #274: Do not print secret content in error message

charts/images.yaml
from v0.1.0 to v0.2.0
/kind bug
Fixes a bug in MCM-openstack in the construction of the neutron client not taking region into account.
Fixes #
```bugfix user
An issue has been fixed which prevented ports from being patched properly after machine creations.
```
=> Upgrade machine-controller-manager-provider-openstack

charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
As described in https://github.com/gardener/gardener-extension-provider-openstack/pull/287, the csi-driver-node logging is verbose and noisy.
Except the livenessprobe container, the csi-driver container is noisy as well. It generates a lot of logs such as:
```
I0524 20:01:44.879641       1 utils.go:81] GRPC request:
I0524 20:01:44.879674       1 identityserver.go:50] Probe() called with req
I0524 20:01:44.885084       1 utils.go:86] GRPC response:
I0524 20:01:54.879767       1 utils.go:80] GRPC call: /csi.v1.Identity/Probe
I0524 20:01:54.879837       1 utils.go:81] GRPC request:
I0524 20:01:54.879872       1 identityserver.go:50] Probe() called with req
I0524 20:01:54.883811       1 utils.go:86] GRPC response:
I0524 20:02:04.879962       1 …
```
=> Reduce the log level of cinder-csi-driver

charts/gardener-extension-admission-openstack/charts/application/templates/rbac.yaml
/kind bug
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/346
Follow-up after https://github.com/gardener/gardener-extension-provider-openstack/pull/280 
```other operator
NONE
```
=> Update the admission-openstack RBAC after cloud provider Secrets validation feature

go.mod, pkg/admission/validator/shoot.go, pkg/apis/openstack/helper/helper.go, pkg/apis/openstack/helper/helper_test.go, pkg/apis/openstack/validation/controlplane.go, pkg/apis/openstack/validation/controlplane_test.go, pkg/controller/controlplane/valuesprovider.go, vendor/modules.txt
/kind cleanup
The version constraints for `floating-subnet` and `floating-subnet-tags` field in the cloud-provider-config to select a floating subnet to pick the floating ip for a load balancer has been removed.
```other operator
The version constraints for `floating-subnet` and `floating-subnet-tags` field in the cloud-provider-config to select a floating subnet to pick the floating ip for a load balancer has been removed.
```
/invite @kon-angelo
=> Remove version constraints for lb config

go.mod, pkg/admission/validator/shoot.go, pkg/apis/openstack/helper/helper.go, pkg/apis/openstack/helper/helper_test.go, pkg/apis/openstack/validation/controlplane.go, pkg/apis/openstack/validation/controlplane_test.go, pkg/controller/controlplane/valuesprovider.go, vendor/modules.txt
/kind cleanup
The version constraints for `floating-subnet` and `floating-subnet-tags` field in the cloud-provider-config to select a floating subnet to pick the floating ip for a load balancer has been removed.
```other operator
The version constraints for `floating-subnet` and `floating-subnet-tags` field in the cloud-provider-config to select a floating subnet to pick the floating ip for a load balancer has been removed.
```
/invite @kon-angelo 
cc @RaphaelVogel
=> [release-v1.19] Remove version constraints for lb config

pkg/apis/openstack/validation/secrets.go, pkg/apis/openstack/validation/secrets_test.go
Enhances the validation of Openstack cloud provider secrets:
* `domainName`, `tenantName`, and `userName` must not contain leading or trailing whitespace.
* `tenantName` must not be longer than 64 characters, see https://docs.openstack.org/api-ref/identity/v3/?expanded=show-project-details-detail.
* `password` must not contain leading or trailing new lines, as they are known to cause issues. Other whitespace characters such as spaces are intentionally not checked for, since there I couldn't find any documentation indicating that they would not be valid.
* `authURL` must be a valid URL if present. 
Fixes # …
=> Enhance validation of cloud provider secrets

Dockerfile, charts/internal/cloud-provider-config/templates/_cloud-provider-config-global.tpl, charts/internal/cloud-provider-config/values.yaml, docs/usage-as-end-user.md, pkg/apis/openstack/validation/secrets.go, pkg/apis/openstack/validation/secrets_test.go, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go, pkg/controller/infrastructure/actuator_delete.go, pkg/controller/infrastructure/actuator_reconcile.go, pkg/internal/infrastructure/templates/main.tpl.tf, pkg/internal/infrastructure/templates/variables.tf, pkg/internal/terraform.go, pkg/internal/terraform_test.go, pkg/openstack/client/client.go, pkg/openstack/credentials.go, pkg/openstack/types.go
/area security
The provider secret for Openstack can contain the keys `applicationCredentialID` and `applicationCredentialSecret` as alternative to authentication with username/password 
Fixes #4 
This PR is depending on a new release of the **machine-controller-manager-provider-openstack** which includes PR https://github.com/gardener/machine-controller-manager-provider-openstack/pull/26
```feature user
add support for application credentials
```
=> add support for application credentials

charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml
/area storage
/kind bug
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/369
```other operator
NONE
```
=> Set minAllowed memory for csi-driver-node containers

pkg/controller/worker/machine_dependencies.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go, pkg/controller/worker/server_groups.go
/kind bug
+ Fixes an issue with servergroups. Prior to the fix, when the servergroups are deleted from a workerpool it would require 2 reconcilliation loops for the change in the shoot's spec to create proper machineclasses.
Minor:
+ change a `map[string]struct{}` used for string lookup to `sets.String`
+ improve the servergroup reverse name lookup by taking into account a trailing `-`.  For example shoots like `shoot_name` and `shoot_name_2` will no longer collide during the reverse lookup. 
Fixes #
```bugfix operator
Fixes an issue where removing server groups from a worker pool would not …
```
=> fix server group removal from worker pool

.ci/pipeline_definitions
/kind task
Push the component-descriptor on head-update 
Fixes #
```other operator
NONE
```
=> push component-descriptor on head update

pkg/apis/openstack/cloudprofile_test.go, pkg/apis/openstack/openstack_suite_test.go, pkg/apis/openstack/types_cloudprofile.go, pkg/apis/openstack/validation/cloudprofile.go, pkg/apis/openstack/validation/cloudprofile_test.go, pkg/apis/openstack/validation/controlplane.go
Allow to change the name and purpose of load balancer classes in `.controlPlaneConfig.loadBalancerClasses[]`. The load balancer classes configuration need still to be semantically equal with the load balancer classes from the CloudProfile.
Add validation to check if there are no load balancer classes with same name and if there are multiple default or private load balancer classes.
```other user
It is now allowed to change the name and purpose of load balancer classes in `.controlPlaneConfig.loadBalancerClasses[]`. The load balancer classes configuration need still to be semantically equal with the load balancer classes from the CloudProfile.
```
/invite …
=> Improve LoadBalancerClass validation

charts/internal/machineclass/templates/machineclass.yaml, docs/usage-as-end-user.md, go.mod, hack/api-reference/api.md, pkg/apis/openstack/types_infrastructure.go, pkg/apis/openstack/v1alpha1/types_infrastructure.go, pkg/apis/openstack/v1alpha1/zz_generated.conversion.go, pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go, pkg/apis/openstack/validation/infrastructure.go, pkg/apis/openstack/validation/infrastructure_test.go, pkg/apis/openstack/zz_generated.deepcopy.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go, pkg/internal/infrastructure/templates/main.tpl.tf, pkg/internal/infrastructure/terraform.go, pkg/internal/infrastructure/terraform_test.go, test/integration/infrastructure/infrastructure_test.go, vendor/modules.txt
Allows the creation of shoots into existing user-managed networks.
Fixes #
```other operator
Shoots can now be deployed in existing Neutron networks. The network can be specified by its ID in the respective shoot's infrastructure configuration.
```
=> Deploy shoots in existing Neutron networks

go.mod, pkg/apis/openstack/helper/scheme.go, pkg/controller/controlplane/valuesprovider.go, pkg/controller/infrastructure/actuator_reconcile.go, pkg/controller/worker/actuator.go, pkg/controller/worker/helper.go, pkg/controller/worker/machine_images.go, pkg/controller/worker/machines.go, pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplaneexposure/ensurer.go, test/tm/generator.go, vendor/modules.txt
/kind cleanup
Similar to gardener/gardener#4280 we should be using Go native error wrapping (available since GO 1.13).
Fixes #305
```NONE
```
/invite @vanjiii
=> Stop using `github.com/pkg/errors`

.golangci.yaml, pkg/admission/validator/webhook.go, pkg/apis/openstack/types_cloudprofile.go, pkg/apis/openstack/types_worker.go, pkg/apis/openstack/v1alpha1/types_worker.go, pkg/controller/dnsrecord/actuator.go, pkg/controller/worker/machine_dependencies_test.go, pkg/internal/terraform.go, pkg/openstack/client/compute.go, pkg/openstack/types.go, test/tm/generator.go
/area quality, dev-productivity
Makes the linter fail on missing or wrong doc comments and a few other common style errors, and fixes all such issues that already exist.
Fixes #
Making the linter fail on missing or wrong doc comments and a few other common style errors consists of enabling `revive` in the `golangci-lint` configuration and excluding certain `revive` errors that we are perhaps not interested in.
I have fixed the following `revive` errors (as regexes that could be included in the `golangci-lint` configuration if desired):
```
- "exported: comment on exported (var|const|type|method|function) .* …
```
=> Make the linter fail on missing or wrong doc comments

pkg/internal/infrastructure/templates/main.tpl.tf
When creating security group rules in newer versions of Openstack, Neutron will modify the request mid-flight when using the max port  range (1-65535) to **None**. In the end the SG rule entries will not specify any port range. As a consequence terraform using in the infrastructure reconciliation will detect that as a change and force the deletion and recreation of the SG rules. 
This PR changes the terraform specification for the affected rules to use nil range values and stop the constant TF reconciliation. 
source: https://bugs.launchpad.net/neutron/+bug/1848213 
Fixes #335
**Release …
=> Remove port ranges from security group rules

charts/internal/cloud-provider-config/templates/_cloud-provider-config-loadbalancer.tpl, charts/internal/cloud-provider-config/templates/_cloud-provider-config-meta.tpl, charts/internal/cloud-provider-config/templates/cloud-provider-config.yaml, charts/internal/cloud-provider-config/values.yaml, hack/api-reference/api.md, pkg/apis/openstack/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/zz_generated.conversion.go, pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go, pkg/apis/openstack/validation/cloudprofile.go, pkg/apis/openstack/validation/cloudprofile_test.go, pkg/apis/openstack/zz_generated.deepcopy.go, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go, pkg/openstack/client/client.go
Allow the configuration of request-timeout for OpenStack clients used by control plane components (cloud-controller-manager and csi-driver). The configuration is done based on the respective cloudprofile value.
Fixes #
```other operator
Allow configuration of request timeout  for control plane components (CCM, CSI) via cloudprofile
```
=> re-introduce request-timeouts for ccm

charts/internal/machine-controller-manager/shoot/templates/clusterrole-machine-controller-manager.yaml
/kind task
Update RBACs to allow GET/LIST/WATCH of VolumeAttachments with the new MCM provider versions.
Fixes #
```other operator
NONE
```
=> Update MCM RBAC permissions for volumeattachments

docs/usage-as-operator.md, hack/api-reference/api.md, pkg/apis/openstack/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/types_cloudprofile.go, pkg/apis/openstack/v1alpha1/zz_generated.conversion.go, pkg/apis/openstack/v1alpha1/zz_generated.deepcopy.go, pkg/apis/openstack/zz_generated.deepcopy.go, pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
The optional field `resolvConfOptions` is added to the `CloudProfileConfig`. If it is set, an additional systemd service will be deployed on the worker nodes to update the file `/etc/resolv.conf` on every change of `/run/systemd/resolve/resolv.conf` and appends a line with the given options.
Fixes #340 
```other operator
Added optional field `resolvConfOptions` to the provider config of the cloud profile to allow to add options to `/etc/resolv.conf` on worker nodes
```
=> Allow to add options to `/etc/resolv.conf` on worker nodes

charts/gardener-extension-admission-openstack/charts/application/templates/validatingwebhook-validator.yaml, charts/gardener-extension-admission-openstack/charts/runtime/templates/secret-cert.yaml
/area quality
/kind bug
Previously when trying to install the admission helm chart without providing `.global.webhookConfig.caBundle` (for example) the helm deployment was failing with an error similar to this one:
```
... at <.Values.global.webhookConfig.caBundle>: wrong type for value; expected string; got interface {}
```
After the change the same installation will fail with a message that is actually desired.
```
... execution error at (gardener-extension-admission-openstack/charts/application/templates/validatingwebhook-validator.yaml:35:17): .Values.global.webhookConfig.caBundle is required
```
Fixes # …
=> Improve the error message when a required part of webhookConfig is missing

charts/images.yaml
With this change Kubernetes clusters with versions >=1.18 and < 1.22 will always get version v1.21.0 of the cloud-controller-manager.
As features will not backported to older versions of ccm we need to use a more recent version (which contains a required  feature: pattern based subnet detection, see https://github.com/kubernetes/cloud-provider-openstack/pull/1375) also for older k8s versions.
```breaking operator
Kubernetes versions >=1.18 and < 1.22 will get cloud-controller-manager with version v1.21.0
```
=> use v1.21.0 for K8s >=1.18 <1.22

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/kind cleanup
Removes deprecated OpenstackMachineClass removal logic
Fixes #
```breaking operator
Removes deprecated OpenstackMachineClass removal logic.
```
=> Remove OpenstackMachineclass cleanup

charts/images.yaml, pkg/controller/infrastructure/actuator_delete.go, pkg/internal/infrastructure/templates/main.tpl.tf
Upgrades `terraformer` image to v2.13.0, a version that uses `terraform` 0.13.
Fixes #
**Release Notes**:
``` other operator github.com/gardener/terraformer #105 @stoyanr
terraform has been upgraded to 0.13.7
```
``` other operator github.com/gardener/terraformer #104 @ialidzhikov
The following terraform provider plugins are updated:
- hashicorp/terraform-provider-aws: 3.54.0 -> 3.63.0
```
``` noteworthy developer github.com/gardener/terraformer #103 @rfranzke
The version for the `equinixmetal` Terraform provider plugin has been updated to `3.1.0`.
```
``` bugfix developer …
```
=> Upgrade terraformer to v2.13.0, a version that uses terraform 0.13

charts/internal/machine-controller-manager/seed/templates/deployment.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml
/kind cleanup
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/422
Ref gardener/gardener#1649
```other operator
NONE
```
=> Remove the "garden.sapcloud.io/role" label from control plane components

charts/internal/machineclass/templates/machineclass.yaml, charts/internal/machineclass/values.yaml, pkg/apis/openstack/validation/shoot.go, pkg/apis/openstack/validation/shoot_test.go, pkg/controller/worker/machines.go
Allows specifying the type of the root volume used in instances and passes that to the MCM extension (as implemented [here](https://github.com/gardener/machine-controller-manager-provider-openstack/pull/43))
Fixes #
```other operator
Provider now supports specifying the volume type for the root disk of nodes.
```
=> Volume type support for root disk of VMs

charts/internal/cloud-provider-config/templates/_cloud-provider-config-networking.tpl, charts/internal/cloud-provider-config/templates/cloud-provider-config.yaml, charts/internal/cloud-provider-config/values.yaml, hack/api-reference/api.md, pkg/apis/openstack/types_infrastructure.go, pkg/apis/openstack/v1alpha1/types_infrastructure.go, pkg/apis/openstack/v1alpha1/zz_generated.conversion.go, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go, pkg/internal/infrastructure/templates/main.tpl.tf, pkg/internal/infrastructure/terraform.go, pkg/internal/infrastructure/terraform_test.go, pkg/openstack/client/networking.go, pkg/openstack/client/types.go
/kind bug
[cloud-provider-openstack](https://github.com/kubernetes/cloud-provider-openstack) offers the possibility to [identify the internal network](https://github.com/kubernetes/cloud-provider-openstack/blob/v1.22.1/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#networking). This PR adds this option to the `cloud-provider-config`
This is necessary so that nodes can identify the correct internal IP when more than one network interface is attached to them.
Fixes gardener/gardener-extension-provider-openstack#372
I have tried to find the right places in the code to make this …
=> Add `internalNetworkName` to cloud-provider-config

pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
Debian derivates like Garden Linux and Ubuntu are using `systemd-resolved` for  network name resolution. This service also contains a full-featured local resolver at `127.0.0.53`.
With this PR, the kubelet uses a separate resolve config file `/etc/resolv-for-kubelet.conf` linked to `/run/systemd/resolve/resolv.conf`. If the cloud profile defines `resolvConfOptions`, the kubelet will use a patched copy of `/run/systemd/resolve/resolv.conf` as already introduced with PR #342. As the kubelet configuration is defined globally for all worker pools, the implementation is a little complicated. It needs to provide the separate `/etc/resolv-for-kubelet.conf` even if the …
=> Use separate resolv.conf for kubelet

charts/internal/machine-controller-manager/seed/templates/clusterrole.yaml
Adds missing RBAC due to the machine-controller-manager-provider-openstack was vendored with mcm v0.43
Fixes #
```other operator
NONE
```
=> update RBAC for mcm v0.43

docs/usage-as-end-user.md, pkg/apis/openstack/validation/shoot.go, pkg/apis/openstack/validation/shoot_test.go, pkg/controller/controlplane/valuesprovider.go, pkg/controller/csimigration/add.go, pkg/controller/healthcheck/add.go, pkg/openstack/types.go, pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/merge squash
This PR implements support for `gardener/gardener`'s `WorkerPoolKubernetesVersion` feature gate. As explained in https://github.com/gardener/gardener/issues/3501#issuecomment-1009061189, it
- adds validation to prevent using kubelet versions lower than the CSI migration version (note that this ensures that the feature is only usable once the cluster with its control plane and **all** its worker pools was upgraded to at least the CSI migration version).
- adapts the `controlpane` webhook to use the effective kubelet version when computing the CSI migration feature gate names.
Part of gardener/gardener#3501
**Special …
=> Kubernetes Version Configurability per Worker Pool

charts/images.yaml
/area storage
This PR adds `csi-driver-cinder` for Kubernetes v1.23 to the extension.
```other operator
NONE
```
=> Update `csi-driver-cinder` for kubernetes v1.23

go.mod, go.sum, vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/actuator.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go, vendor/github.com/gardener/gardener/pkg/apis/core/helper/helpers.go, vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/secrets.go, vendor/modules.txt
/area control-plane-migration
/kind bug
Compared to `gardener/gardener@v1.39.0`, `gardener/gardener@v1.39.3` contains the following fixes that are related to the extension library:
- https://github.com/gardener/gardener/pull/5339
- https://github.com/gardener/gardener/pull/5408
```bugfix operator
- github.com/gardener/gardener: v1.39.0 -> v1.39.3
```
=> Vendor gardener/gardener@v1.39.3

charts/gardener-extension-admission-openstack/charts/application/templates/rbac.yaml, charts/gardener-extension-admission-openstack/charts/application/templates/serviceaccount.yaml, charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml, charts/gardener-extension-admission-openstack/charts/runtime/templates/serviceaccount.yaml, charts/gardener-extension-admission-openstack/values.yaml, docs/deployment.md
/area security
This PR adds: 
- The ability to configure the admission deployment to use service account token volume projection ([ref](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection)).
- The ability to configure a user instead of a service account subject in the `clusterrolebinding` definition when using a "virtual garden" setup. This will enable other possibilities for authentication to the virtual garden, i.e., leveraging [oidc-webhook-authenticator](https://github.com/gardener/oidc-webhook-authenticator).
Fixes #
This PR is related …
=> Add support for sa token volume projection in admission charts

go.mod, go.sum, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/update.go, vendor/modules.txt
/kind bug
Compared to `gardener/gardener@v1.39.4`, `gardener/gardener@v1.39.5` contains the following fixes that are related to the extension library:
- https://github.com/gardener/gardener/pull/5455
```bugfix operator
- github.com/gardener/gardener: v1.39.4 -> v1.39.5
```
=> Vendor gardener/gardener@v1.39.5

charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml
/kind bug
This PR explicitly sets the `default` serviceaccount to the `admission` deployment when its own serviceaccount is not required.
Fixes a bug which occurs when the `admission` component is deployed with a serviceaccount and then upgraded with `helm upgrade` and `values.yaml` that do not require the serviceaccount anymore. What happens is that the serviceaccount is deleted and `helm` patches the deployment by sending `serviceAccountName: nil`, but there is a duplicate field named `serviceAccount` (deprecated by k8s) which holds the old `serviceAccountName` value and Kubernetes defaults `serviceAccountName` to it. This prevents the upgrade because the said serviceaccount …
=> Fix serviceaccount defaulting during helm upgrade

charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
/area/storage
/kind/enhancement
Cherry pick of #402 on release-v1.23.
#402: Increase cpu resources for csi-driver
```other operator
The CPU limit of `csi-driver-node/csi-driver` is increased from 50m to 100m to allow bigger bursts.
```
=> [release-v1.23] Automated cherry pick of #402: Increase cpu resources for csi-driver

charts/gardener-extension-admission-openstack/charts/application/templates/validatingwebhook-validator.yaml, charts/gardener-extension-admission-openstack/values.yaml, example/40-validatingwebhookconfiguration.yaml
This PR adds an object selector for provider type label in the `gardener-extension-admission-openstack` webhook. This helps in filtering out only resources having provider type `openstack` for validation.
Fixes part of gardener/gardener#4932
Related to gardener/gardener#5472
```other operator
The `gardener-extension-admission-openstack` webhook now contains an object selector for provider type label. Please make sure you are running `gardener@v1.42` or later before enabling this.
```
=> Add object selector for provider type in the `gardener-extension-admission-openstack` webhook 

charts/images.yaml
/kind/bug
Cherry pick of #411 on release-v1.24.
#411: [ci:component:github.com/gardener/machine-controller-manager:v0.43.0->v0.43.1]
``` bugfix user github.com/gardener/machine-controller-manager #687 @himanshu-kun
typo stopping scaleDown disabling during cluster rollout is fixed
```
=> [release-v1.24] Automated cherry pick of #411: [ci:component:github.com/gardener/machine-controller-manager:v0.43.0->v0.43.1]

cmd/gardener-extension-provider-openstack/app/app.go, pkg/controller/infrastructure/actuator.go, pkg/controller/infrastructure/actuator_delete.go, pkg/controller/infrastructure/actuator_migrate.go, pkg/controller/infrastructure/actuator_reconcile.go, pkg/controller/infrastructure/add.go, pkg/internal/terraform.go
/area security
This PR enables projected token mounts for the `terraformer` pods.
Part of gardener/gardener#4659
Part of gardener/gardener#4878
```other operator
The `terraformer` pod deployed as part of shoot control planes is now using auto-rotated `ServiceAccount` tokens when communicating with the seed cluster.
```
=> Use projected token mount for terraformer

pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/area/usability
/kind/bug
Cherry pick of #415 on release-v1.24.
#415: Keep kubelet's `--cloud-provider` flag even for 1.23+
```bugfix user
An issue preventing load balancers from being functional for K8s 1.23 clusters has been fixed.
```
=> [release-v1.24] Automated cherry pick of #415: Keep kubelet's `--cloud-provider` flag even for 1.23+

charts/internal/shoot-system-components/charts/csi-driver-node/templates/podsecuritypolicy.yaml
/kind bug
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/510.
We were not able to reproduce similar PSP issue for K8s >= 1.19 but even though that I think it still makes sense to keep the PSP up-to-date and to have it reflecting the needed permissions.
```other operator
NONE
```
=> Allow projected volumes in the csi-driver-node PSP

charts/internal/machine-controller-manager/seed/mcm-monitoring-dashboard.json, charts/internal/seed-controlplane/charts/cloud-controller-manager/ccm-observability-dashboard.json, charts/internal/seed-controlplane/charts/csi-driver-controller/csi-driver-controller-dashboard.json
/area monitoring
/squash
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/503.
```other operator
The monitoring dashboards provided by this extension:
- are now using UTC by default (instead of the browser time)
- do no longer auto refresh by default
```
=> Improve grafana dashboards

.dockerignore, Makefile, cmd/gardener-extension-admission-openstack/app/app.go, cmd/gardener-extension-provider-openstack/app/app.go, vendor/k8s.io/component-base/version/verflag/verflag.go, vendor/modules.txt
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/525
Part of https://github.com/gardener/gardener/issues/2703
```feature developer
provider-openstack and admission-openstack components now support `--version` flag that prints the component version information and useful metadata.
```
=> Add --version flag for components

cmd/gardener-extension-provider-openstack/app/app.go, pkg/cmd/options.go, pkg/webhook/cloudprovider/add.go
Update the cloudprovider mutating webhook to use an `objectSelector` based on the specific labels of the `cloudprovider` secret. This way the webhook will only react on updates to the `cloudprovider` particular secret  which reduces load and avoid situations where an issue with the extension may prevent any and all updates to secrets (even other secrets than `cloudprovider`).
This is automatically enabled when the `gardener-version` is larger than `1.42` which is the version that gardenlet started adding the necessary labels to the secret.
Fixes #
```other operator
The …
```
=> update cloudprovider webhook for objectSelector

charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml
/area quality
/kind bug
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/535
```other operator
NONE
```
=> Fix incorrect validator deployment value

pkg/apis/openstack/validation/shoot.go, pkg/apis/openstack/validation/shoot_test.go
/area auto-scaling
remove validation which avoids worker grp to specify min=0.
Fixes #
```other operator
NONE
```
=> Remove validation avoiding sfz

charts/images.yaml
/area/control-plane
/kind/bug
/kind/enhancement
Cherry pick of #446 on release-v1.25.
#446: Update CCM version to 1.23.1
```other operator
The following image is updated:
- k8scloudprovider/openstack-cloud-controller-manager: v1.23.0 -> v1.23.1
```
=> [release-v1.25] Automated cherry pick of #446: Update CCM version to 1.23.1

charts/internal/shoot-system-components/requirements.yaml
This PR fixes a typo i stumbled upon in `./charts/internal/shoot-system-components/requirements.yaml`.
=> fix typo in requirements.yaml

charts/internal/cloud-provider-config/templates/_cloud-provider-config-loadbalancer.tpl
/area quality
/kind bug
It fixes the correctness of the generated `ini` file. Everything that is not a boolean or integer value has to be quoted. Some parsers may still parse the file but some are not able to.
```bugfix operator
Fixes missing quotes in the generated cloud-provider-config file
```
Signed-off-by: Felix Breuer <fbreuer@pm.me>
=> fix cloud-provider-config generation

charts/images.yaml
/kind bug
Currently the ControlPlane resource for K8s 1.24 Shoot cluster fails to be reconciled with:
```yaml
lastError:
description: 'Error reconciling controlplane: could not apply control plane
chart for controlplane ''shoot--foo--bar/bar'': could not
inject chart ''cloud-controller-manager'' images: could not find image "cloud-controller-manager"
opts runtime version v1.21.10 target version 1.24.1'
lastUpdateTime: "2022-06-13T16:04:43Z"
```
```bugfix user
An issue preventing ControlPlane resource to be successfully reconciled for K8s 1.24 Shoots is now fixed.
```
=> Fix Shoot creation for K8s 1.24

charts/images.yaml
/area/control-plane
/kind/bug
Cherry pick of #459 on release-v1.26.
#459: Fix Shoot creation for K8s 1.24
```bugfix user
An issue preventing ControlPlane resource to be successfully reconciled for K8s 1.24 Shoots is now fixed.
```
=> [release-v1.26] Automated cherry pick of #459: Fix Shoot creation for K8s 1.24

charts/images.yaml
/kind bug
Use openstack cloud-controller-manager `v1.22.0` for Shoots with target k8s version `v1.23.x`.
Ref: https://github.com/kubernetes/cloud-provider-openstack/issues/1795
```bug operator
Use openstack cloud-controller-manager `v1.22.0` for Shoots with target k8s version `v1.23.x`. [ref](https://github.com/kubernetes/cloud-provider-openstack/issues/1795)
```
=> Use occm `v1.22.0` for `v1.23.x` shoots

charts/images.yaml
openstack-cloud-controller-manager@v1.23.3 contains the backport of the fix for https://github.com/kubernetes/cloud-provider-openstack/issues/1795#issuecomment-1176130631. Hence it should be safe to switch to occm@1.23  again for K8s 1.23 Shoots.
```other operator
The following image is updated:
- k8scloudprovider/openstack-cloud-controller-manager: v1.22.0 -> v1.23.3 (for Kubernetes 1.23 Shoots)
```
=> Use openstack-cloud-controller-manager@v1.23.3 for K8s 1.23 Shoots

charts/images.yaml
/area storage
```other operator
The following images are updated:
- docker.io/k8scloudprovider/cinder-csi-plugin: v1.20.0 -> v1.20.3 (for Kubernetes 1.20 Shoots)
- docker.io/k8scloudprovider/cinder-csi-plugin: v1.24.0 -> v1.24.2 (for Kubernetes 1.24 Shoots)
```
=> Upgrade cinder-csi-plugin

charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-driver.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/podsecuritypolicy.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
`PodSecurityPolicy` is deprecated and will be disabled in kubernetes v1.25+.
End-users are provided an option to migrate their PSPs before upgrading and disable the `PodSecurityPolicy` admission plugin in the ShootSpec. 
In that case, we should stop deploying our PSPs as well.
- This PR stops deploying PSPs related to `provider-openstack` if the plugin is disabled in the Shoot
Part of https://github.com/gardener/gardener/issues/5250
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/587
/hold
Depends on #484 
```breaking operator
Please make sure …
```
=> Don't deploy `PSP`s when `PodSecurityPolicy` plugin is disabled 

charts/images.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotcontents.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshots.yaml
/area storage
/kind technical-debt
Fixes #
similar to gardener/gardener-extension-provider-gcp#460
```other operator
The following images are updated:
- k8s.gcr.io/sig-storage/csi-provisioner: v2.0.4 -> v3.2.1 (for kubernetes >= 1.20)
- k8s.gcr.io/sig-storage/csi-attacher: v3.3.0 -> v3.5.0
- k8s.gcr.io/sig-storage/csi-resizer: v0.5.0 -> v1.5.0
- k8s.gcr.io/sig-storage/csi-snapshotter: v3.0.3 -> v4.2.1 (for kubernetes >= 1.20)
- k8s.gcr.io/sig-storage/snapshot-validation-webhook: v3.0.3 -> v4.2.1 (for kubernetes >= 1.20)
- k8s.gcr.io/sig-storage/snapshot-controller: v3.0.3 -> v4.2.1 (for kubernetes >= 1.20)
- …
```
=> Update various kubernetes-csi images

test/integration/bastion/bastion_test.go, test/integration/infrastructure/infrastructure_test.go
With https://github.com/gardener/gardener-extension-provider-openstack/pull/484 , `log.Info` had wrong argument signature.
Fixes #
```other operator
```
=> Fix log formatting

charts/internal/machine-controller-manager/seed/templates/vpa.yaml, charts/internal/machine-controller-manager/seed/values.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/vpa.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-driver-controller-vpa.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/vpa.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/values.yaml
/area auto-scaling
Limits the range of maximum allowed resource requests to ensure that pods are schedulable
Fixes #
```other operator
NONE
```
=> Adds MaxAllowed for VPA objects

README.md, charts/internal/cloud-provider-config/values.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml, docs/usage-as-end-user.md, docs/usage-as-operator.md, example/10-fake-shoot-controlplane.yaml, example/30-controlplane.yaml, example/30-worker.yaml, hack/api-reference/api.json, hack/api-reference/api.md, hack/api-reference/config.json, pkg/controller/controlplane/valuesprovider_test.go, pkg/webhook/controlplane/ensurer_test.go
/kind cleanup
Part of https://github.com/gardener/gardener-extension-provider-aws/issues/595
```breaking operator
provider-openstack no longer supports Shoots with Кubernetes version < 1.17.
```
=> Removes support for kubernetes < 1.17 for OpenStack extension provider

charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml
/kind bug
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/604
```other operator
NONE
```
=> Correct the metricsPort check for admission-openstack deployment

charts/images.yaml
/kind bug
#502 updated the CCM images.
The v1.22 image was wrongly updated. There is no v1.22.1 image published.
With this PR, we fall back to v1.22.0 image for v1.22.x Shoots.
Fixes #
```other operator
NONE
```
=> Use CCM `v1.22.0` image for `1.22.x` Shoots

README.md, docs/usage-as-end-user.md, docs/usage-as-operator.md, example/30-controlplane.yaml, example/30-dnsrecord.yaml, example/30-infrastructure.yaml, example/30-worker.yaml
Updates Gardener API Core version in examples and markdowns to `core.gardener.cloud/v1beta1`
Fixes #
```other operator
NONE
```
=> Update API Core version in examples to core.gardener.cloud/v1beta1

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
With this PR the labels in a worker pool will be used to annotate the OpenStack server instance (in addition to the node object - that already being done). Because in OpenStack the metadata key is more restrictive than K8s we need to transform the key by replacing illegal characters.
Fixes #
```other operator
Allow adding the `Labels` of a worker pool to the corresponding OpenStack Instance.
```
=> allow passthrough of worker labels to VM metadata

pkg/controller/infrastructure/actuator_delete.go, pkg/internal/infrastructure/infrastucture.go, pkg/openstack/client/mocks/client_mocks.go, pkg/openstack/client/networking.go, pkg/openstack/client/types.go
All infrastructure routes within the workers node range are deleted during the deletion process. This lets the deletion still succeed when the cloud controller manager is not there anymore.
Fixes #
```other operator
All infrastructure routes within the workers node range are deleted during the deletion process. This lets the deletion still succeed when the cloud controller manager is not there anymore.
```
=> delete infrastructure routes in case ccm is not there

charts/gardener-extension-admission-openstack/charts/application/templates/mutatingwebhook-mutator.yaml, charts/gardener-extension-admission-openstack/charts/application/templates/rbac.yaml, example/50-mutatingwebhookconfiguration.yaml
/area quality
/kind bug
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/657.
See https://github.com/gardener/gardener-extension-provider-aws/pull/657
```bugfix user
An issue causing admission-openstack to fail CREATE/UPDATE requests for Shoots from the `core.gardener.cloud/v1alpha1` API is now fixed.
```
=> Do not fail a request for a Shoot from the core.gardener.cloud/v1alpha1 API

pkg/controller/infrastructure/actuator_delete.go, pkg/internal/infrastructure/infrastucture.go, pkg/internal/infrastructure/terraform.go
/kind bug
Fixes #
```other operator
Fix a nil pointer exception in the route deletion method when shoots are using the deprecated `Worker` field.
```
=> fix nil pointer exception in route cleanup

pkg/controller/infrastructure/actuator_delete.go, pkg/internal/infrastructure/infrastucture.go, pkg/internal/infrastructure/terraform.go
/kind bug
Cherry pick of #532 on release-v1.30.
#532: fix nil pointer exception in route cleanup
```other operator
Fix a nil pointer exception in the route deletion method when shoots are using the deprecated `Worker` field.
```
=> [release-v1.30] Automated cherry pick of #532: fix nil pointer exception in route cleanup

go.mod, go.sum, vendor/github.com/gardener/gardener-extension-networking-calico/pkg/apis/calico/v1alpha1/types_network.go, vendor/modules.txt
/kind bug
Update calico version to `v1.27.1`.
This is required because in previous calico versions the `backend` field was not omitted when set to `nil`.
This update will avoid setting `backend: null` in the shoot spec when the shoot mutator webhook in the infrastructure extension is called which leads to an error during validation.
```
error: error validating "STDIN": error validating data: unknown object type "nil" in Shoot.spec.networking.providerConfig.backend; if you choose to ignore these errors, turn validation off with --validate=false
```
Fixes #
```other operator
Update calico version …
```
=> update calico version to v1.27.1

charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
The verbose level for the csi-driver-nodes is currently set to 4 and contains a lot of noise.
By introducing the `vmodule` settings, the periodic logs are removed now.
Fixes #
```other operator
Reduce noise in csi-driver-node logs
```
=> Reduce noise in csi-driver-node logs

pkg/internal/infrastructure/infrastucture.go, pkg/internal/infrastructure/infrastucture_test.go
/kind bug
Do not make update requests for the routes if no changes are necessary.
Fixes #
```other operator
Skip router update requests to remove routes if no change is necessary.
```
=> return early if no route changes

.golangci.yaml, charts/charts.go, pkg/apis/config/loader/loader.go, pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
Introduce the deprecated check back and fix linting errors
Fixes #
```other operator
NONE
```
=> add linting check for deprecated variables

hack/api-reference/api.md, pkg/apis/openstack/types_infrastructure.go, pkg/apis/openstack/v1alpha1/types_infrastructure.go, pkg/apis/openstack/v1alpha1/zz_generated.conversion.go, pkg/internal/infrastructure/templates/main.tpl.tf, pkg/internal/infrastructure/terraform.go, pkg/internal/infrastructure/terraform_test.go
/area useability
/kind api-change
We recently developed the [Gardener ACL extension](https://github.com/stackitcloud/gardener-extension-acl) which can block external traffic to gardener via IP ranges.  
In order for gardener to function on openstack, we also need to add the Gateway routerIP to the list of allowed IP ranges. Otherwise gardener is not able to connect via reverse VPN to the cluster and we get internal error messages.
This PR exposes the IP to the RouterStatus so we are able to use it and feed it into our allowed list.
```feature developer
Expose Router IP address to RouterStatus.IP
```
=> expose routerIP to infrastructure.status

pkg/controller/bastion/actuator_reconcile.go
/kind task
after https://github.com/gardener/gardenctl-v2/pull/186 PR, the last error will be printed during the bastion creation 
fix typo in case misleading, fix public ip to floating ip 
`Still waiting: Error while waiting for Bastion shoot--abc-os/cli-urta3zkr to become ready: error during reconciliation: Error reconciling Bastion: instance or public ip address not ready yet`
Fixes #
```other operator
```
=> fix typo public ip to floating ip

charts/internal/machine-controller-manager/seed/templates/deployment.yaml
/area scalability
/kind bug
An incorrect `containerName` in the vpa object caused the container not beeing controlled by the vpa. In decent largish clusters this can cause the container to get `OOMKilled` as it only has 32Mi of memory.
Fixes #
~Helm diff might a bit large as my tar or whatever it is causing it produces a different output. But it does work 100%.~
```bugfix operator
An incorrect container name in the machine-controller-manager Deployment caused the container not beeing controlled by the vpa.
```
=> fix containerName of provider-openstack within the mcm Deployment

charts/images.yaml
/area security
Add CVE categorisation/runtime contexts for managed OCI images of `MCM` and `mcm-provider-openstack`.
Fixes #
```other operator
NONE
```
=> Add CVE runtime context for `MCM` and `mcm-provider-openstack`

charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotcontents.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshots.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshotclasses.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshotcontents.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshots.yaml
/area storage
/kind bug
This PR copies the legacy CRDs in `charts/internal/shoot-system-components/charts/csi-driver-node/templates` (updated by https://github.com/gardener/gardener-extension-provider-openstack/pull/531) to `charts/internal/shoot-crds/charts/volumesnapshots/templates` and marks the legacy with `resources.gardener.cloud/mode=Ignore` again.
Fixes https://github.com/gardener/gardener-extension-provider-openstack/issues/565
cc @MartinWeindel 
```bugfix user
A bug has been fixed that caused the `snapshot.storage.k8s.io` CRDs in shoot clusters to flap between two different versions.
```
=> Fix flapping `snapshot.storage.k8s.io` CRDs

charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotcontents.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshots.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshotclasses.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshotcontents.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/crd-volumesnapshots.yaml
/area storage
/kind bug
Cherry pick of #566 on release-v1.31.
#566: Fix flapping `snapshot.storage.k8s.io` CRDs
```bugfix user
A bug has been fixed that caused the `snapshot.storage.k8s.io` CRDs in shoot clusters to flap between two different versions.
```
=> [release-v1.31] Automated cherry pick of #566: Fix flapping `snapshot.storage.k8s.io` CRDs

charts/gardener-extension-admission-openstack/charts/application/templates/mutatingwebhook-mutator.yaml
/kind bug
It modifies the webhook in-place so as to not make shoot mutations. We opted to change the webhook watched resources instead of deleting the mutating webhook, so as to avoid manual operations needed by operators to remove the mutating webhook and to make it easier to re-enable it in the future.
Fixes #
```bugfix operator
Disable overlay webhook to prevent issues with overloading Neutron API with route requests.
```
=> Disable overlay webhook completely

README.md, charts/images.yaml, pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/area open-source usability
/exp intermediate
/topology garden seed shoot
/merge squash
This PR adds support for Kubernetes 1.26 to the extension.
Part of https://github.com/gardener/gardener/issues/6773
* ~~Depends on to be opened PR for K8s 1.26 client creation, hence, PR is in draft state.~~
* I have successfully validated the functionality as follows:
* :white_check_mark: Create new clusters with versions < 1.26
* :white_check_mark: Create new clusters with version  = 1.26
* :white_check_mark: Upgrade old clusters from version 1.25 to version 1.26
* :white_check_mark: Delete clusters with versions < 1.26
* …
=> Support for Kubernetes v1.26

charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml
This PR adds the `node.gardener.cloud/critical-component` label to `csi-driver-node` introduced in https://github.com/gardener/gardener/pull/7406
Part of https://github.com/gardener/gardener/issues/7117
https://github.com/gardener/gardener/pull/7406 is merged
```feature user
`csi-driver-node` is marked as a node-critical component. With this, workload pods are only scheduled to a `Node` if it runs a ready `csi-driver-node` pod.
```
=> Mark csi-driver-node as node-critical component 

pkg/admission/mutator/shoot.go, pkg/admission/mutator/shoot_test.go
Remove the setting of enabling the snat traffic to the upstream dns sever because this is now the default option in the calico extension for non-overlay cluster and thus no longer required to be explicitly set in the openstack provider extension.
Furthermore do existing shoot clusters now keep also their set overlay field values when the `EnableOverlayAsDefault` field for calico or cilium is set. 
Fixes #
```other operator
none
```
=> remove snat settings since they are no longer required

charts/images.yaml
Fixes #
```other operator
Update `cloud-controller-image` v1.24.5 -> v1.24.6
```
```other operator
Update `cloud-controller-image` v1.25.3 -> v1.25.5
```
```other operator
Update `cloud-controller-image` v1.26.0 -> v1.26.2
```
=> Update CCM Images

pkg/controller/worker/machine_dependencies.go, pkg/controller/worker/machine_dependencies_test.go
The `DeployMachineDependencies` and `CleanupMachineDependencies` funcs were deprecated with https://github.com/gardener/gardener/pull/6290.
https://github.com/gardener/gardener/pull/7600 is about to remove these deprecates funcs.
This PR is minimal adaptation to non-deprecated variants. A TODO describing the further adaptation is being added.
N/A
N/A
```other operator
NONE
```
=> Switch to the non-deprecated funcs of the WorkerDelegate

go.mod, go.sum, pkg/controller/healthcheck/add.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/controller.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/healthcheck/reconciler.go, vendor/modules.txt
/kind bug
For the reasoning, please check https://github.com/gardener/gardener/issues/6775#issuecomment-1432816749 and https://github.com/gardener/gardener/pull/7660.
We need to add `ShootSystemComponentsHealthy` to conditionTypesToRemove.
Fixes #
```bugfix operator
The stale healthcheck conditions from the extension are now properly cleaned up.
```
```
- github.com/gardener/gardener: v1.65.0 -> v1.65.3
```
=> [release-v1.32] Vendor `gardener@1.65.3` and add `ShootSystemComponentsHealthy` to `conditionTypesToRemove`

charts/images.yaml
This PR is needed to support IPv6 single stack and avoid DockerHub pull limits as it uses copied images from Gardener GCR instead.
Part of https://github.com/gardener/ci-infra/issues/619
```other operator
Switched images from DockerHub to copies in Gardener GCR
```
=> Switched from DockerHub to Gardener GCR

charts/images.yaml
With https://github.com/kubernetes/cloud-provider-openstack/issues/1540 `openstack-cloud-controller-manager` and `cinder-csi-plugin` images are pushed to GCR. See https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-provider-os/images.yaml
Hence, we do no longer need to maintain our copies for 1.24, 1.25, 1.26.
See above.
N/A
```other operator
provider-openstack does no longer use Gardener GCR copies for `openstack-cloud-controller-manager` and `cinder-csi-plugin` in versions 1.24, 1.25 and 1.26. Instead, the upstream GCR container …
```
=> Switch back to upstream GCR images for `openstack-cloud-controller-manager` and `cinder-csi-plugin`

charts/internal/cloud-provider-config/templates/_cloud-provider-config-loadbalancer.tpl, charts/internal/cloud-provider-config/values.yaml
Update OCCM LB config according to latest testing
Fixes #
```other operator
Cloud-controller-manager Loadbalancer configuration has been updated: `monitorDelay: 60s -> 20s`, `monitorMaxRetries: 5 -> 2`
```
=> update occm lb settings

charts/images.yaml
/kind impediment
For K8s version 1.25.x the condition for selecting the `csi-driver-manila` image was not correct.
Fix for error message:
```txt
could not inject chart 'csi-driver-manila-controller' images: could not find image "csi-driver-manila" opts runtime version v1.24.9 target version 1.25.6 ] Operation will be retried.
```
Fixes #
```other operator
NONE
```
=> Fix image version selection for csi-driver-manila

pkg/controller/controlplane/valuesprovider.go
/area quality
/kind bug
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/735
See above
N/A
```bugfix operator
An issue causing provider-openstack to wrongly delete the `extensions.gardener.cloud:provider-openstack:csi-snapshot-validation` ClusterRole and ClusterRoleBinding from the Seed cluster on every Shoot deletion is now fixed.
```
=> Do not delete `csi-snapshot-validation` ClusterRole and ClusterRoleBinding from the wrong cluster (Seed cluster) when deleting Shoot

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go, pkg/openstack/types.go
Improve the hash calculation for machine-deployments. We should not include the providerConfig in the hash calculation and instead let the extension decide what is "important" enough to trigger a node rollout. This is a breaking change because changing the hash will trigger a node rollout. 
To ease the transition we include an annotation that shoot owners can use  to preserve the old hash calculation. This is done to allow shoot owners the freedom to make the node rollout at their discretion. Only worker pools using `server groups` should be affected by the change in the hash. However using the new annotation means **all** `machineLabels` will trigger a rollout. …
=> Improve worker hash calculation

charts/gardener-extension-admission-openstack/charts/runtime/templates/service.yaml, charts/gardener-extension-admission-openstack/values.yaml
/area high-availability
The following Service is adapted to be topology-aware:
- `gardener-extension-admission-openstack` - the Service is consumed by `virtual-garden-kube-apiserver` and `gardener-apiserver` for the webhook communication
Part of https://github.com/gardener/gardener/issues/6718
N/A
```other operator
The `gardener-extension-admission-openstack` Service in the `gardener-extension-admission-openstack` chart can now be configured to be topology-aware.
```
=> Make the `gardener-extension-admission-openstack` Service topology-aware

charts/internal/machine-controller-manager/seed/templates/deployment.yaml
/kind cleanup
/platform aws
Fixes #
```doc dependency
The flags which went out-of-support in MCM v0.49.0 have been cleaned up from MCM deployment yaml.
```
=> Remove out-of-support flags from deployment Yaml

pkg/internal/infrastructure/templates/main.tpl.tf
This reverts commit 432c3c887b94276bc4344256efdd3ab2fef5e142.
Revert the port restriction because it interferes with bastion operations. 
Fixes #
```other operator
Fix an issue with bastion not establishing connection after the security group restriction to NodePort ranges.
```
=> Revert "restrict port (#608)"

charts/internal/seed-controlplane/charts/csi-driver-manila-controller/templates/deployment-controller.yaml, charts/internal/seed-controlplane/charts/csi-driver-manila-controller/values.yaml, charts/internal/shoot-system-components/charts/csi-driver-manila/templates/daemonset-node.yaml, charts/internal/shoot-system-components/charts/csi-driver-manila/templates/storageclass.yaml, charts/internal/shoot-system-components/charts/csi-driver-manila/values.yaml
+ Current storageclasses have now `volumeBindingMode: WaitForFirstConsumer`
+ Adds topology awareness support for Manila
+ Default deployment now is with TopologyAwareness
+ Fix an issue where the `nodeaz` was not computed correctly when enabled
+ Adds the following storageclasses:
- A storage class without specifying the `availability` ( leaves it up to the Manila Scheduler to make decision about the location) 
- Exclusive storageclasses per region (`*-constrain-*` variants). These storageclasses will make it so that both the provisioning and the scheduling of workloads using these volumes is exclusive to the target zone.  …
=> add topology support for manila

pkg/controller/healthcheck/add.go
This reverts commit f082bfb90d695a1a8037a26a6b9d073a4fe06324.
/platform openstack 
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/748
Fixes #
```other operator
Remove the error code check from `NodesChecker` to prevent nil pointer panic.
```
=> Revert "Consider errors from NodesChecker for finding user related issues"

pkg/controller/bastion/actuator_reconcile.go
This PR will make it so that the bastion controller binds FIPs from the same subnet as the router. We can potentially change the logic to use processing logic similar as with `FloatingPoolSubnetName`, but for simplicity this PR chooses the router subnet. The downside of that choice is that we depend on that particular subnet for available FIPs. 
Fixes #615 
```other operator
The bastion with try to reserve Floating IPs from the router's external subnet
```
=> specify fip subnet based on router

charts/internal/seed-controlplane/charts/csi-driver-manila-controller/templates/deployment-controller.yaml
/kind bug
Add observability config map for manila CSI driver
Fixes #
```other operator
Add observability configuration for Manila CSI Driver. 
```
=> manila observability

charts/gardener-extension-admission-openstack/charts/runtime/templates/service.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-service.yaml
/area high-availability
See https://github.com/gardener/gardener/pull/7933
N/A
N/A
```other operator
NONE
```
=> topology-aware routing: Adapt to the upstream annotation change in K8s 1.27

pkg/apis/openstack/validation/infrastructure.go, pkg/apis/openstack/validation/infrastructure_test.go, pkg/controller/controlplane/valuesprovider.go
/kind bug
The admission webhook disallows changing network settings in the infrastructure config. But it also contains the `shareNetwork` section needed for CSI Manila support. This PR allows to enable or disable the share network for existing clusters.
Additionally it fixes the deletion of the CSI Manila controller deployment as a wrong name was specified ("csi-driver-manila-controller" instead of "csi-driver-controller-manila")
Fixes #
```bugfix user
Allow changing share network section in `InfrastructureConfig` for existing cluster.
```
=> Allow changing share network section

charts/images.yaml
Updates to a newer version of the external-provisioner where https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/121 is fixed.
Fixes #
```other dependency
The following dependencies were updated:
- registry.k8s.io/sig-storage/csi-provisioner v3.4.0 -> v3.4.1
```
=> Update external-provisioner to version 3.4.1

Dockerfile, Makefile
When we run:
```
❯ docker run eu.gcr.io/gardener-project/gardener/extensions/provider-openstack:v1.33.0 --version
gardener-extension v1.33.0-dev
```
```
❯ docker run eu.gcr.io/gardener-project/gardener/extensions/admission-openstack:v1.34.0-dev-1e2db5512c995812f9dbaa97a573ccf7738d2af9 --version
gardener-extension v1.34.0-dev
```
This PR fixes this issue by using effective version.
Also with this PR, docker images built by make docker-images are tagged and built with a version including the commit hash (exactly like the images built by the pipeline).
Fixes #
```other operator …
```
=> Set effective version when building images

charts/images.yaml
Update the cloud-provider-openstack image references.
Fixes #
```other operator
Update cloud-provider-openstack images v1.25.5 -> v1.25.6
```
```other operator
Update cloud-provider-openstack images v1.26.2 -> v1.26.3
```
=> update cloud provider openstack

charts/images.yaml
/kind bug
Cherry pick of #646 on release-v1.35.
#646: [ci:component:github.com/gardener/machine-controller-manager:v0.49.2->v0.49.3]
``` bugfix operator github.com/gardener/machine-controller-manager #834 @ialidzhikov
Included `UnavailableReplicas` in determining if a machine deployment status update is needed
```
=> [release-v1.35] Automated cherry pick of #646: [ci:component:github.com/gardener/machine-controller-manager:v0.49.2->v0.49.3]

charts/internal/shoot-system-components/charts/csi-driver-manila/templates/storageclass.yaml
/kind bug
If the infrastructure cannot be reconciled successfully (e.g. out of quota), the share network cannot be created and the rendering of the charts fail with 
```
Error reconciling ControlPlane: could not apply control plane shoot chart for controlplane 'shoot--hc-ci--a9a998-orc/a9a998-orc': could not render chart: could not render chart 'shoot-system-components' in namespace 'kube-system': render error in "shoot-system-components/charts/csi-driver-manila/templates/storageclass.yaml": template: shoot-system-components/charts/csi-driver-manila/templates/storageclass.yaml:13:21: executing "shoot-system-components/charts/csi-driver-manila/templates/storageclass.yaml" at …
```
=> Fix rendering of CSI manila storageclass if creating infrastructure fails.

pkg/controller/infrastructure/actuator.go, pkg/controller/infrastructure/add.go
/kind bug
Missing after https://github.com/gardener/gardener-extension-provider-openstack/pull/653
Fixes #
```other operator
NONE
```
=> add missing actuator initialize

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go, pkg/openstack/types.go
/area auto-scaling
Fixes #
```other operator
machineDeployment will have the label `topology.cinder.csi.openstack.org/zone` when created.
```
=> CSI topology label on MachineDeployment creation to allow scale-up

pkg/controller/infrastructure/infraflow/delete.go
/kind bug
Fix a bug introduced with https://github.com/gardener/gardener-extension-provider-openstack/pull/656 about selecting the correct field between `worker` and `workers`
Fixes #
```other operator
NONE
```
=> fix choosing worker cidr

pkg/openstack/client/client.go
/kind bug
As briefly discussed [here](https://github.com/gardener/gardener-extension-provider-openstack/pull/563#discussion_r1331585432), openstack clients constructed for cloudprofiles don't honor cloudprofile specific TLS settings. A suitable HTTPClient is created but isn't used by the provider. 
This PR is to fix this issue.
=> Honor cloudprofile specific TLS settings

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go, pkg/openstack/types.go
Allows autoscaling for manila volumes
Fixes #
```other operator
Add manila topology labels to machines. This enables scaling from 0 for pods depending on manila volumes.
```
=> add manila labels

README.md, charts/images.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/cloud-controller-manager.yaml, charts/internal/seed-controlplane/charts/cloud-controller-manager/values.yaml, docs/operations/operations.md, pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/kind cleanup
Drop support for kubernetes < 1.24 for Openstack extension provider
Part of https://github.com/gardener/gardener/issues/8405
```breaking operator
`provider-openstack` no longer supports Shoots or Seeds with Кubernetes version < 1.24.
```
=> Drop support for Shoots with Kubernetes version < 1.24

pkg/controller/infrastructure/infraflow/reconcile.go, pkg/internal/infrastructure/templates/main.tpl.tf
Adds convenient descriptions to security group rules in terraformer.
N.A.
Fixes #
```other developer
Added description to openstack security group rules.
```
=> add convenient description to security group rules

charts/images.yaml
Fixes #
```other operator
updated image csi-provisioner -> `v3.6.0`
```
```other operator
updated image csi-attacher -> `v4.4.0`
```
```other operator
updated image csi-resizer -> `v1.9.0`
```
```other operator
updated image snapshot-controller -> `v6.3.0`
```
```other operator
updated image livenessprobe -> `v2.11.0`
```
```other operator
updated image cloud-provider-openstack `v1.27.1`-> `v1.27.2`
```
```other operator
updated image cinder-csi-plugin `v1.27.1`-> `v1.27.2`
```
```other operator
updated image manila-csi-plugin `v1.27.1`-> `v1.27.2`
```
=> update image definitions

imagevector/images.yaml
/area storage
/kind bug
Fixes https://github.com/kubernetes-csi/external-snapshotter/issues/927
```other operator
Update external-snapshotter to v6.3.1
```
=> Update external-snapshotter to v6.3.1

charts/images.yaml
/area storage
/kind bug
Cherry pick of #682 on release-v1.37.
#682: Update external-snapshotter to v6.3.1
```other operator
Update external-snapshotter to v6.3.1
```
=> [release-v1.37] Automated cherry pick of #682: Update external-snapshotter to v6.3.1

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/csi-snapshot-validation-webhook-deployment.yaml
Adds a healthcheck to the snapshot-validation webhook server. Has the disadvantage that the logs will be spammed with messages like:
```
2023/10/30 18:30:38 http: TLS handshake error from 10.180.0.17:53028: EOF
```
This is to prevent issues like those introduced with external-snapshoter v6.3.0 where the server never started successfully and the bug took too long to detect.
Fixes #
```other operator
Add tcp healthcheck to csi-snapshot-validation-webhook
```
=> readiness check

charts/internal/shoot-system-components/charts/csi-driver-manila/templates/storageclass.yaml, charts/internal/shoot-system-components/charts/csi-driver-manila/values.yaml
Use nfs v4.1 by default on manila mounts. This is due to the lack of proper support by netapp for v4.2. In subsequent PRs we plan to integrate the manila storage classes better with the `storageClassDefinitions` in the cloudprofile. 
Fixes #
```other operator
Use NFS version v4.1 as mount options for manila storage classes
```
=> use nfs v4.1 by default

charts/internal/shoot-system-components/charts/csi-driver-manila/templates/storageclass.yaml
Fixes #
```feature user
Add manila auto-topology storage class
```
```breaking user
The zonal manila storage classes are now deprecated and will be removed in a future version.
```
=> Add Manila autoTopology storage class

imagevector/images.yaml
/kind bug
Cherry pick of #692 on release-v1.38.
#692: [ci:component:github.com/gardener/machine-controller-manager-provider-openstack:v0.15.0->v0.15.1]
```other operator github.com/gardener/machine-controller-manager #866 @himanshu-kun
The default `machine-safety-orphan-vms-period` has been reduced from 30m to 15m.
```
```bugfix operator github.com/gardener/machine-controller-manager #866 @himanshu-kun
Removes `node.machine.sapcloud.io/not-managed-by-mcm` annotation from nodes managed by the MCM.
```
=> [release-v1.38] Automated cherry pick of #692: [ci:component:github.com/gardener/machine-controller-manager-provider-openstack:v0.15.0->v0.15.1]

pkg/admission/mutator/shoot.go, pkg/admission/mutator/shoot_test.go
/kind bug
Fix a crash, when a shoot that is updated has an empty overlay config. 
Fixes #
```bugfix operator
Fix a crash, when a shoot that is updated has an empty overlay config. 
```
=> Fix panic in mutating webhook, when overlay config is empty in old shoot.

pkg/admission/mutator/shoot.go, pkg/admission/mutator/shoot_test.go
/kind bug
Cherry pick from https://github.com/gardener/gardener-extension-provider-openstack/pull/694
Fix a crash, when a shoot that is updated has an empty overlay config. 
Fixes #
```bugfix operator
Fix a crash, when a shoot that is updated has an empty overlay config. 
```
=> [release-v1.38] Fix panic, when overlay config is empty in old shoot.

.ci/component_descriptor
Set COMPONENT_PREFIXES env variable to fix upgrade PRs.
It is needed, as gardener/gardener is older than v1.84.0
Fixes #
related to https://github.com/gardener/gardener/pull/8755
```other operator
NONE
```
=> set COMPONENT_PREFIXES env variable to fix upgrade PRs

pkg/webhook/controlplane/ensurer.go
/kind cleanup
Similar to https://github.com/gardener/gardener-extension-provider-aws/pull/876
N/A
N/A
```other operator
NONE
```
=> Use `extensionswebhook.EnsureFileWithPath` instead of custom `appendUniqueFile` func

Makefile
Neither `docker-images-provider` nor `docker-images-admission` exist. Use `image` instead of `images` in both to make `make docker-images` work again.
=> Fix subtarget names of docker-images target

pkg/controller/bastion/actuator_reconcile.go, pkg/openstack/client/compute.go, pkg/openstack/client/mocks/client_mocks.go, pkg/openstack/client/types.go
Fixes #
```other operator
Allows bastion to use images by ID instead of just by name.
```
=> allow bastion to work with ids

.ci/pipeline_definitions
Adds component-responsible label to the component descriptor. This way, the responsibles will also be recognized for findings on images that are referenced, not only for those that are built.
Also, simplify by referring to the maintainer team.
=> Set responsible label in component descriptor

pkg/controller/infrastructure/actuator.go
Fixes #
```other operator
provider-openstack will calculate a shoot's Egress CIDRs on infrastructure reconciliation.
```
=> Expose egressCIDRs in provider status

pkg/controller/worker/machines.go, pkg/controller/worker/machines_test.go
/area auto-scaling
This PR adds cluster-autoscaler options for worker groups from workers to machine deployments. These options allow users to specify some cluster-autoscaler specific for worker groups
Fixes partially gardener/autoscaler#240
- `Autoscaler` will read these values from annotations in the `machineDeployment` (ref: https://github.com/gardener/autoscaler/pull/257)
- These values are specified in the shoot via `spec.provider.workers.clusterAutoscaler` and are added to the worker (ref: https://github.com/gardener/gardener/pull/9245)
```other operator
NodeGroupAutoscalingOptions can …
```
=> Add cluster-autoscaler options to machine deployment

.ci/testruns/default/templates/testrun.yaml, Makefile, test/integration/bastion/bastion_test.go
/area quality
/kind bug
To support newer GardenLinux versions in our bastion test we need to enable ssh via userData
Fixes #
The reason for the userData being b64 encoded is that the [format type of the field is byte](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#:~:text=%27string%27%20with%20format%3Dbyte%20(base64%20encoded)). 
So we actually have to define them in plaintext.
The same has to be done for the bastion tests of the other providers.
```other bugfix
Fix userData of bastion test
```
=> Fix bastion userData

charts/internal/cloud-provider-config/templates/cloud-provider-config-loadbalancer.tpl
The extension doesn't allow setting a loadbalancer's lb-method attribute. The default for lb-method is `ROUND_ROBIN`, but the ovn loadbalancer provider only supports `SOURCE_IP_PORT`. This renders ovn unusable. Since `SOURCE_IP_PORT` is to be used when and only when the provider is ovn, and ovn doesn't work without it, it seems reasonable to just hard-code the value.
> `lb-method` The load balancing algorithm used to create the load balancer pool. [...] If lb-provider is set to "ovn" the value must be set to SOURCE_IP_PORT.
(https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/using-openstack-cloud-controller-manager.md#load-balancer) …
=> Set lb-method="SOURCE_IP_PORT" when using "ovn" loadbalancer provider

charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml, charts/gardener-extension-admission-openstack/values.yaml
This PR enhances the admission chart by the option to set a `priorityClassName`.
Part of https://github.com/gardener/gardener/issues/9936.
```other operator
A `priorityClassName` can now be set for the admission deployment via the `gardener-extension-admission-openstack` Helm chart.
```
=> [admission] Add `priorityClassName`

pkg/controller/infrastructure/infraflow/delete.go, pkg/controller/infrastructure/infraflow/utils.go
/kind bug
Fixes #
```other operator
Fix an issue with share network reconciliation not calculating number of existing share networks correctly.
```
=> [release 1.41] fix an issue with share network reconciliation not calculating number of existing share networks correctly

pkg/cmd/options.go, pkg/webhook/controlplane/add.go
Part of issue https://github.com/gardener/gardener/issues/9864, followup for g/g PR #9981. Use `ObjectSelector` in controlplane webhook to limit mutator calls for unrelated resource changes.
Part of https://github.com/gardener/gardener/issues/9864
```other operator
Starting with gardenlet >= v1.98.0, use controlplane webhook object selector to limit mutator calls.
```
=> Add object selector to controlplane webhook with version constraint

pkg/cmd/options.go, pkg/webhook/cloudprovider/add.go
/kind cleanup
https://github.com/gardener/gardener-extension-provider-openstack/pull/816 didn't clean up everything possible related to the change in gardener/gardener: https://github.com/gardener/gardener/pull/10027
Part of https://github.com/gardener/gardener/issues/9864
I am leaving the the param on the `WebhookSwitchOptions` as the gardenerVersion param will be used with https://github.com/gardener/gardener-extension-provider-openstack/pull/797.
```other operator
NONE
```
=> Clean up cloudprovider webhook after dropping the gardener version check

charts/gardener-extension-admission-openstack/charts/application/templates/rbac.yaml, cmd/gardener-extension-admission-openstack/app/app.go, docs/usage/usage.md, pkg/admission/validator/credentialsbinding.go, pkg/admission/validator/credentialsbinding_test.go, pkg/admission/validator/shoot.go, pkg/admission/validator/webhook.go
/area security ipcei
/label ipcei/workload-identity
Part of https://github.com/gardener/gardener/issues/9586
cc @vpnachev 
```feature user
The admission webhook now validates `CredentialsBinding`s.
```
=> [GEP-26] CredentialsBinding validation via admission webhook

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/daemonset.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/secret.yaml, imagevector/images.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
- Update cloudprovider images (including CSI driver images)
- Remove use of credentials from the nodeserver daemonset
- Remove deprecated v1.25 images
Fixes #
```other operator
Update cloud-provider-openstack images and remove credential use from nodeserver
```
=> Update cloud-provider-openstack images and remove credential use from nodeserver

charts/gardener-extension-admission-openstack/charts/application/templates/rbac.yaml, docs/usage/usage.md, pkg/admission/validator/shoot.go, pkg/admission/validator/shoot_test.go, pkg/apis/openstack/helper/scheme.go, pkg/apis/openstack/validation/controlplane.go
/kind api-change
Make the Azure provider extension aware of the `CloudProfile` field and the option to provide `NamespacedCloudProfile` references in the `shoot.Spec.CloudProfile`.
See also [GEP-25](https://github.com/gardener/gardener/issues/9504) and [this PR](https://github.com/gardener/gardener/pull/10093).
Related to https://github.com/gardener/gardener/issues/9504
```feature operator
Enable support for the field `shoot.Spec.CloudProfile` alongside `shoot.Spec.CloudProfileName` and enable the future use of `NamespacedCloudProfile`.
```
=> [GEP-25] Enable Shoot cloudProfile reference as complement to cloudProfileName

imagevector/images.yaml
Revert the removal of v1.25 images. V1.25 deprecation will be followed up in a proper PR. 
Fixes #
```other operator
NONE
```
=> revert v1.25 image removal

docs/operations/operations.md, pkg/apis/openstack/validation/cloudprofile.go, pkg/apis/openstack/validation/cloudprofile_test.go, pkg/apis/openstack/validation/controlplane.go, pkg/apis/openstack/validation/controlplane_test.go
We are adding a new openstack region that uses the OVN networking stack, and also the octavia OVN loadbalancer provider that has some worthwhile [advantages](https://docs.openstack.org/ovn-octavia-provider/latest/admin/driver.html). But since OVN is also still [missing features](https://docs.openstack.org/octavia/latest/user/feature-classification/index.html) we want to also allow the well known amphora provider in parallel.
Currently the cloudprofile/controlplane validation does not allow multiple entries for a region.
The Shoot spec validation has always required to specify a loadBalancerProvider even when there is only a single choice, the behavior for a given …
=> Allow multiple loadBalancerProviders as the default and for a region

pkg/controller/worker/actuator.go
The error message 
```
[...]: failed to create openstack seedClient: Authentication failed
```
is confusing. There openstack client is actually an openstack client against the Shoot's infrastructure. Maybe we wanted to express a failure creating an openstack client using a seedClient (which is a K8s client)? IMO there is no need to provide such internal details.
N/A
N/A
```other operator
NONE
```
=> Improve confusing error message

.test-defs/infrastructure-test.yaml, pkg/controller/infrastructure/infraflow/access/networking_access.go, pkg/controller/infrastructure/infraflow/reconcile.go, test/integration/infrastructure/infrastructure_test.go
/area testing
Parallelize infrastructure tests
Fixes #
```other operator
NONE
```
=> parallel tests

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/secret.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
/kind bug
Fix an issue after https://github.com/gardener/gardener-extension-provider-openstack/pull/864 that prevented the successful deployment of the csi-controller and csi-node on k8s <=1.27
Fixes #
```other operator
Fix a bug that prevented the Cinder CSI from working on shoots with kubernetes version less than v1.28.
```
=> Fix k8s <=v1.27 deployment of csi-driver-node

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/secret.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
/kind bug
Cherry pick of #875 on release-v1.42.
#875: Fix k8s <=v1.27 deployment of csi-driver-node
```other operator
Fix a bug that prevented the Cinder CSI from working on shoots with kubernetes version less than v1.28.
```
=> [release-v1.42] Automated cherry pick of #875: Fix k8s <=v1.27 deployment of csi-driver-node

pkg/apis/openstack/validation/infrastructure.go, pkg/apis/openstack/validation/infrastructure_test.go, pkg/controller/infrastructure/infraflow/delete.go, pkg/controller/infrastructure/infraflow/reconcile.go
/kind bug
Fixes #
```other operator
Fix an issue where provider-openstack required permissions for share network operations even when not required by the `InfrastructureConfig`.
```
=> forbid disabling share networks

pkg/controller/infrastructure/infraflow/delete.go, pkg/controller/infrastructure/infraflow/reconcile.go
/kind bug
Fixes #https://github.com/gardener/gardener-extension-provider-openstack/issues/890
```other operator
Fix an issue where the deletion with the flow reconciler would fail if the network was already deleted.
```
=> fix deletion when network doesn't exist

.test-defs/apply-flow-openstack.yaml, .test-defs/bastion-test.yaml, .test-defs/infrastructure-test.yaml, .test-defs/provider-openstack.yaml, Dockerfile, go.mod
/area quality
/kind cleanup
Update to go 1.23.3
Fixes #
```other dependency
Update go to version 1.23.3
```
=> Update to go 1.23.3

pkg/admission/validator/shoot_test.go, pkg/apis/openstack/validation/shoot.go
Enforce restriction with regards to IPv6 support
Fixes #
This check replace https://github.com/gardener/gardener/pull/10716.
```other operator
Added validation to prevent IPv6-only/dual-stack clusters as they are not supported, yet.
```
=> Enforce restriction with regards to IPv6 support

.test-defs/apply-flow-openstack.yaml, .test-defs/bastion-test.yaml, .test-defs/infrastructure-test.yaml, .test-defs/provider-openstack.yaml, Dockerfile, go.mod
/area quality
Update golang versions
Fixes #
```other operator
NONE
```
=> Update golang versions

cmd/gardener-extension-provider-openstack/app/app.go, pkg/cmd/options.go, pkg/webhook/controlplane/add.go
/kind cleanup
Remove gardener version constraint for controlplane webhook object selector.
Followup cleanup to https://github.com/gardener/gardener/issues/9864.
```other operator
```
=> Cleanup object selector version constraint

imagevector/images.yaml
/kind bug
Updates CSI images with the new release that fixes https://github.com/kubernetes/cloud-provider-openstack/issues/2677
Fixes #
```other operator
Update Cinder CSI `v1.30.1` -> `v1.30.2` for shoots on v1.30.x
```
```other operator
Update Cinder CSI `v1.30.1` -> `v1.31.2` for shoots on v1.31.x
```
=> update csi images

pkg/controller/infrastructure/infraflow/utils.go
/kind cleanup
Cleanup the infraflow error message if multiple matches are found for a name. 
The findExisting helper has a filter parameter, which however is never used. Thus drop it and clean up the error message.
The old code resulted in an error like the following:
`error reconciling infrastructure: 1 error occurred:\n\t* failed to \"ensure security group\": error multiple matches: found matches: [0x123456 0x23456]`. With the change this becomes `error reconciling infrastructure: 1 error occurred:\n\t* failed to \"ensure security group\": error multiple matches: found 2 matches for name "shoot--example--example"`.
=> infraflow: Improve "error multiple matches" message

pkg/admission/mutator/namespacedcloudprofile.go, pkg/admission/mutator/namespacedcloudprofile_test.go, pkg/admission/mutator/webhook.go, pkg/admission/validator/namespacedcloudprofile.go, pkg/admission/validator/namespacedcloudprofile_test.go, pkg/admission/validator/webhook.go, pkg/apis/openstack/validation/cloudprofile.go
Support custom machine images and versions in `NamespacedCloudProfile`s. For that, add mutating and validating admission webhooks.
Part of https://github.com/gardener/gardener/issues/9504, followup to https://github.com/gardener/gardener/pull/10629.
/cc @timuthy 
```other operator
Add `NamespacedCloudProfile` admission mutation and validation to support custom machine images and types.
```
=> Add `NamespacedCloudProfile` validation and mutation webhooks

charts/gardener-extension-admission-openstack/charts/application/templates/serviceaccount.yaml, charts/gardener-extension-admission-openstack/charts/application/values.yaml, charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml, charts/gardener-extension-admission-openstack/charts/runtime/values.yaml
/kind task
The PR #901 removed the support for deploying the admission controller in the local `provider-extensions` setup.
It is enabled again similar as for the provider-aws.
Fixes #
Follow-up of #901
```other operator
NONE
```
=> Readd support for deploying admission controller in local extensions setup

charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-provisioner.yaml
/area storage
/kind bug
Re-adds missing permission to the csi-provisioner RBAC we deploy
```other operator
Fix an issue where the CSI-Provisioner was missing 'patch' permissions on PVs
```
=> re-add missing patch permission to csi-provisioner

charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-provisioner.yaml
/area storage
/kind bug
Re-adds missing permission to the csi-provisioner RBAC we deploy
```other operator
Fix an issue where the CSI-Provisioner was missing 'patch' permissions on PVs
```
=> [Release v1.43] re-add missing patch permission to csi-provisioner

imagevector/images.yaml
from v0.19.0 to v0.20.1
/kind bug
MCM update from v0.19.0 to v0.20.1.
Increase VM status check timeout to 1200 seconds.
Fixes #
```other operator
MCM update to v0.20.1: Increase VM status check timeout to 1200 seconds
```
=> Hotfix 1.43 - cherry pick mcm update

cmd/gardener-extension-provider-openstack/app/app.go, pkg/cmd/options.go, pkg/webhook/seedprovider/add.go, pkg/webhook/seedprovider/ensurer.go, pkg/webhook/seedprovider/ensurer_test.go
/kind cleanup
Rename packages, loggers and variables according to the new name.
Which issue(s) this PR fixes:
Followup renaming of https://github.com/gardener/gardener/issues/10017.
```other operator
NONE
```
=> Rename to `seedprovider` webhook

charts/internal/seed-controlplane/charts/csi-driver-controller/templates/deployment-csi-driver-controller.yaml, charts/internal/seed-controlplane/charts/csi-driver-controller/values.yaml, pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
/kind bug
Adds a limit to the listVolume call made by the attacher. The csi-driver call to cinder may return only a limited amount of volumes per page and without the max-entries these additional volumes will not be processed.
Fixes #
```other operator
Add max-entries to the csi-attacher arguments. 
```
=> add max-entries to attacher

pkg/controller/infrastructure/infraflow/access/networking_access.go
/area quality
Adds the last error seen for Wait functions to the returned error if a context is done. 
If a user adds servers into the network created by the extension and attaches a floating IP to it, openstack will report with an 409 error which is explicitly filtered out in the functions. If a timeout occurs and the context is canceled, infraflow will only report context canceled in the infrastructure `status.lastError` field. Therefore is hard to understand why the task failed in the first place.
Example of the new error format:
```yaml
status:
lastError:
description: "Error deleting Infrastructure: 1 error occurred:\n\t* failed to
\"delete router interface\": context deadline …
```
=> fix(infraflow): report last error for wait functions

pkg/admission/validator/cloudprofile.go, pkg/admission/validator/namespacedcloudprofile.go, pkg/apis/openstack/validation/cloudprofile.go, pkg/apis/openstack/validation/cloudprofile_test.go
/area quality
This PR adjusts the CloudProfile validation so that all MachineImages in the CloudProfile map to a valid image in the CloudProfileConfig.
Follow up to https://github.com/gardener/gardener-extension-provider-azure/pull/1020.
Fixes #
```other operator
Validate that all MachineImages in the CloudProfile map to a valid MachineImage in the CloudProfileConfig 
```
=> Fix cloud profile machineImages validation

README.md
/area documentation
/kind task
It adds the conformance test results badge for Kubernetes v1.32.
Part of: https://github.com/gardener/gardener/issues/11020
/cc @LucaBernstein 
```other operator
NONE
```
=> docs: Add conformance test results badge for Kubernetes v1.32

pkg/apis/openstack/validation/cloudprofile.go, pkg/apis/openstack/validation/cloudprofile_test.go
/area quality
/kind bug
The `CloudProfileConfig.machineImages[].versions[].regions[]` field is optional and can be empty.
We need to adjust our validation. 
Fixes https://github.com/gardener/gardener-extension-provider-openstack/issues/1021
```bugfix operator
Fix CloudProfile validation in case `CloudProfileConfig.machineImages[].versions[].regions[]` is empty
```
=> Fix cloudProfile validation

cmd/gardener-extension-provider-openstack/app/app.go, cmd/gardener-extension-provider-openstack/app/migrations.go
/area security
/kind cleanup
After the Machine Controller Manager was moved from the provider extension codebases to the core, the charts that define the component's resources have been deleted, as well as most resources that have been deployed to that point - [PR reference](https://github.com/gardener/gardener-extension-provider-openstack/pull/711).
However, some ClusterRoles and ClusterRoleBindings that were used for the component still remain on certain seeds.
This PR adds a function to purge those, since they are not in use anymore.
The ClusterRoles|ClusterRoleBindings in question are named in the following way:
```
extensions.gardener.cloud:provider-openstack:<shoot-name>:machine-controller-mana …
```
=> Purge unused Machine Controller Manager RBAC resources

pkg/openstack/client/client.go
/area quality
Enable appCredential authentication using AppName in addition to appID.
Fixes https://github.com/gardener/gardener-extension-provider-openstack/issues/1069
```bugfix operator
Enable appCredential authentication using AppName in addition to appID
```
=> Fix auth with ApplicationCredential Name

pkg/webhook/infrastructure/mutator.go, pkg/webhook/infrastructure/mutator_test.go, test/integration/infrastructure/infrastructure_test.go
Fixes #
```breaking operator
Update the defaults for the infrastructure controller. Unless opted out per shoot or per seed, the infrastructure controller will now by default reconcile using the flow implementation. In future release v1.50.0 we will disable reconciliation via terraform. 
```
=> swap defaults for flow

pkg/webhook/controlplane/ensurer.go, pkg/webhook/controlplane/ensurer_test.go
/kind bug
The starting of `update-resolv-conf.path` can happen after the update of `/run/systemd/resolve/resolv.conf` with the valid configuration. The following has been observed where the file has been updated 4 sec before the start of `update-resolv-conf.path`:
```
cat /etc/resolv-for-kubelet.conf
#
#
#
#
search .
options rotate timeout:1
```
instead of:
```
cat /etc/resolv.conf
#
#
#
#
nameserver 10.191.8.2
nameserver 10.191.8.3
search <name>
options rotate timeout:1
```
This can lead to calico and other components' downtime because of faulty DNS resolution.
Fixes #782 
/cc @Kostov6  …
=> Fix failure because of race conditions for `update-resolv-conf.service`

.test-defs/infrastructure-test.yaml
/area quality
In the past we had some integration test failures caused by timeout.
This PR increases the timeout from 0.5h to 1h.
Fixes #
```other operator
NONE
```
=> Increase infrastructure-test timeout
