gardener/gardener-extension-provider-openstack

pkg/validator/shoot_validator.go
Small changes to harmonize the use of the validationContext during validation. 
/cc @timuthy 
```improvement operator
Use validationContext consistently during validation
```
=> Use validation context consistently

test/tm/generator.go
Fix TODO in tm generator.
Fixes #
```improvement operator
NONE
```
=> Nit: fix TODO in tm generator

pkg/apis/openstack/validation/cloudprofile_test.go
Unify using `k8s.io/utils/pointer` pkg.
```improvement operator
NONE
```
=> Nit: Unify using k8s.io/utils/pointer pkg

README.md
/area Documentation
Fixes #
```improvement operator
NONE
```
=> Adjust version disclaimer message

Makefile, pkg/controller/worker/helper.go, pkg/controller/worker/machine_dependencies.go, pkg/controller/worker/machines_test.go
/kind task
Add "SKIP_FETCH_TOOLS=1" to make test.
```improvement operator
NONE
```
=> Add "SKIP_FETCH_TOOLS=1" to make test

docs/usage-as-end-user.md
Add documentation regarding rate limits.
See https://github.com/gardener/gardener/issues/3120
=> Add end-user rate limit documentation

.test-defs/infrastructure-test.yaml, .test-defs/provider-openstack.yaml, Dockerfile
/kind technical-debt
Updates the images to the eu.grc.io golang image mirror and circumvent dockerhub rate limits
```improvement operator
```
=> update golang image to eu.gcr.io mirror

docs/usage-as-end-user.md
/area TODO
/kind TODO
Fixes #
```other operator
```
=> improve infrastructure config documentation

docs/usage-as-end-user.md
/area TODO
/kind TODO
Fixes #
```other operator
```
=> correct typo

docs/usage-as-end-user.md
/area documentation
Fixes #
```doc operator
NONE
```
=> update docs for application credentials

go.mod, go.sum, vendor/github.com/gardener/gardener/extensions/pkg/controller/controlplane/genericactuator/actuator.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_restore.go, vendor/github.com/gardener/gardener/pkg/apis/core/helper/helpers.go, vendor/github.com/gardener/gardener/pkg/apis/core/v1beta1/helper/helper.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/component/kubeapiserver/kube_apiserver.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/controlplane.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/secrets.go, vendor/modules.txt
/kind/bug
/area/control-plane-migration
Cherry pick of #390 on release-v1.23.
#390: Vendor gardener/gardener@v1.39.3
```bugfix operator
- github.com/gardener/gardener: v1.39.0 -> v1.39.3
```
=> [release-v1.23] Automated cherry pick of #390: Vendor gardener/gardener@v1.39.3

example/20-crd-extensions.gardener.cloud_bastions.yaml, go.mod, go.sum, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/actuator_reconcile.go, vendor/github.com/gardener/gardener/extensions/pkg/controller/worker/genericactuator/update.go, vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/types_bastion.go, vendor/github.com/gardener/gardener/pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go, vendor/github.com/gardener/gardener/pkg/operation/botanist/component/extensions/crds/templates/crd-bastion.tpl.yaml, vendor/modules.txt
/kind/bug
Cherry pick of #393 on release-v1.23.
#393: Vendor gardener/gardener@v1.39.5
```bugfix operator
- github.com/gardener/gardener: v1.39.3 -> v1.39.5
```
=> [release-v1.23] Automated cherry pick of #393: Vendor gardener/gardener@v1.39.5

.test-defs/infrastructure-test.yaml
Similar to https://github.com/gardener/gardener/pull/5478
```other operator
NONE
```
=> Replace -ginkgo.noColor with -ginkgo.no-color

charts/images.yaml
Update CCM version to prevent certain issues with loadbalancers.
Fixes #
```other operator
The following image is updated:
- k8scloudprovider/openstack-cloud-controller-manager: v1.23.0 -> v1.23.1
```
=> Update CCM version to 1.23.1

README.md
=> Fix the broken conformance tests link

.ci/pipeline_definitions
/area TODO
/kind TODO
Fixes #
```other developer
NONE
```
=> Assign Responsibles for the compliance issues

charts/images.yaml
/kind bug
Adopts the fix for https://github.com/kubernetes/cloud-provider-openstack/issues/1935 for K8s 1.24.
```other operator
The following image is updated:
- k8scloudprovider/openstack-cloud-controller-manager: v1.24.2 -> v1.24.3
```
=> Upgrade github.com/kubernetes/cloud-provider-openstack

.test-defs/bastion-test.yaml, .test-defs/infrastructure-test.yaml, .test-defs/provider-openstack.yaml, Dockerfile, Makefile, go.mod, pkg/openstack/client/compute.go
Fixes #
```other operator
Update go version `v1.18.3` -> `v1.19.2`
```
=> update go version

test/integration/infrastructure/infrastructure_test.go
/area testing
Adds the gardener priority class
Fixes #
```other operator
NONE
```
=> Fix integration tests

charts/images.yaml
/kind cleanup
Fixes #
```other operator
Remove deprecated images
```
=> remove < 1.20 images

pkg/controller/controlplane/valuesprovider.go, pkg/controller/controlplane/valuesprovider_test.go
/kind bug
Cherry pick of #521 on release-v1.30.
#521: do not configure cloud routes if overlay is used
```other operator
Disable configuring cloud routes when overlay network is used.
```
=> [release-v1.30] Automated cherry pick of #521: do not configure cloud routes if overlay is used

pkg/internal/infrastructure/templates/main.tpl.tf, test/integration/infrastructure/infrastructure_test.go
/area quality
/kind bug
See #546 
Fixes #546 
```other operator
NONE
```
=> get existing router via ID

charts/images.yaml
/kind task
Update CSI dependencies to latest releases
```other operator
Update CSI dependencies to latest releases
```
=> Update CSI dependencies to latest releases

charts/gardener-extension-admission-openstack/values.yaml
/kind bug
Fix indentation.
Fixes #
```other operator
NONE
```
=> fix values.yaml

.test-defs/bastion-test.yaml, .test-defs/infrastructure-test.yaml, .test-defs/provider-openstack.yaml, Dockerfile
Update golang to v1.19.4
```other operator
Update golang to 1.19.5
```
=> Update golang to v1.19.5

.ci/pipeline_definitions
/area delivery
Similar to https://github.com/gardener/gardener-extension-provider-azure/pull/618
Fixes #
```other developer
NONE
```
=> replace kaniko

pkg/webhook/controlplane/ensurer.go
=> Address TODO

.test-defs/bastion-test.yaml, .test-defs/infrastructure-test.yaml, .test-defs/provider-openstack.yaml, Dockerfile, go.mod
Fixes #
```other operator
Update golang to `v1.20.4`
```
=> update go v1.20.4

imagevector/images.yaml
Fixes #
```dependency operator
updated image csi-provisioner -> `v3.6.1`
```
```dependency operator
updated image csi-attacher -> `v4.4.1`
```
```dependency operator
updated image csi-resizer -> `v1.9.1`
```
```dependency operator
updated image cloud-provider-openstack -> `v1.26.4`
```
```dependency operator
updated image cloud-provider-openstack -> `v1.27.3`
```
```dependency operator
updated image cloud-provider-openstack -> `v1.28.1`
```
=> update image definitions

Makefile
Fixes #
```other operator
NONE
```
=> update image rules

Makefile
/kind bug
Fix typo in makefile targets
Fixes #
```other operator
NONE
```
=> fix targets

charts/gardener-extension-admission-openstack/charts/runtime/templates/deployment.yaml
/kind bug
Fixes #
```other operator
Admission controller will be deployed with the LEADER_ELECTION_NAMESPACE set to the pod namespace
```
=> specify leader-election ns

imagevector/images.yaml
```other operator
Update terraformer to v2.25.0
```
=> Upgrade terraformer in v1.39

pkg/controller/infrastructure/actuator.go, pkg/controller/infrastructure/actuator_reconcile.go, test/integration/infrastructure/infrastructure_test.go
/area monitoring
/kind test
- Test exposure of egress cidrs
Fixes #
```other operator
NONE
```
=> Add egressCIDRs test

charts/internal/seed-controlplane/charts/cloud-controller-manager/templates/servicemonitor.yaml
/area monitoring
/kind bug
Cherry pick of #788 on release-v1.40.
#788: Fix indentation in CCM ServiceMonitor
```bugfix operator
Fixes a monitoring configuration issue that caused false CCM-down alerts to fire.
```
=> [release-v1.40] Automated cherry pick of #788: Fix indentation in CCM ServiceMonitor

example/20-crd-vpa.yaml
/area testing
/kind technical-debt
Fixes #
```other operator
Update the VPA CRD used for testing locally
```
=> update vpa crd

pkg/webhook/infrastructure/mutator.go
/kind bug
Fixes #
```other operator
Fix a bug that would migrate shoots away from terraform during control-plane migration. This would occur only if the seed was marked to use the flow reconciler for new shoots.
```
=> fix an issue where shoots would be migrated to flow during cp-migration

pkg/webhook/infrastructure/mutator.go
/kind bug
Fixes #
```other operator
Fix a bug that would migrate shoots away from terraform during control-plane migration. This would occur only if the seed was marked to use the flow reconciler for new shoots.
```
=> [Release 1.41] fix an issue where shoots would be migrated to flow during cp-migration

pkg/controller/infrastructure/actuator.go
/kind bug
Fix case where nil instead of the actual error was returned
Fixes #
```other bugfix
Fix case where nil instead of the actual error was returned
```
=> Return err instead of nil

charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotclasses.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshotcontents.yaml, charts/internal/shoot-crds/charts/volumesnapshots/templates/crd-volumesnapshots.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/clusterrole-csi-provisioner.yaml, charts/internal/shoot-system-components/charts/csi-driver-node/templates/csi-snapshot-validation-webhook.yaml, imagevector/images.yaml
Fixes #
```other operator
Update CSI sidecar containers to latest version.
```
=> Update CSI sidecars to latest version

Makefile, pkg/apis/config/loader/loader.go, pkg/apis/openstack/validation/shoot.go, pkg/controller/worker/machines.go, pkg/internal/terraform.go, pkg/openstack/client/client.go, pkg/openstack/types.go
/area quality
Add gosec as sast makefile target
Fixes #
```other dependency
Add gosec as sast makefile target
```
=> Introduce gosec

pkg/openstack/client/networking.go
/kind bug
Depending on how the infrastructure in openstack was created the router port (interface) may have different owner references. A list of possible values for router interfaces can be found in the [openstack SDK](https://github.com/openstack/openstacksdk/tree/master) source code: https://github.com/openstack/openstacksdk/blob/4.0.1/openstack/cloud/_network.py#L2133
Currently only ports with owner `network:router_interface` are returned when calling `GetRouterInterfacePort`. If a subnet does not have a port with the `network:router_interface` owner for the associated router, flow attempts to create a new port. However, this creation fails because a router port for the subnet …
=> fix(openstack/networking): filter router interfaces by all possible owners (#284)

imagevector/images.yaml
/kind bug
MCM update from v0.19.0 to v0.20.1.
Increase VM status check timeout to 1200 seconds.
Fixes #
```bugfix user
MCM update to v0.20.1: Increase VM status check timeout to 1200 seconds
```
=> Hotfix - cherry pick mcm update

pkg/controller/infrastructure/infraflow/delete.go, pkg/controller/infrastructure/infraflow/reconcile.go
/kind bug
Fixes #
```other operator
Ignore not found errors on resource deletion during infrastructure reconciliation.
```
=> ignore not found errors on resource deletion

.test-defs/apply-flow-openstack.yaml, .test-defs/bastion-test.yaml, .test-defs/infrastructure-test.yaml, .test-defs/provider-openstack.yaml, Dockerfile, go.mod
Fixes #
```other operator
Update golang to v1.24.0
```
=> update golang to v1.24

pkg/controller/bastion/actuator_reconcile.go
/kind bug
Fixes https://github.com/gardener/gardener-extension-provider-openstack/issues/993
```other operator
Locate the first ipv4 instead of using the first available FIP in bastion controller
```
=> locate ipv4 for external fip in bastion controller

.ci/pipeline_definitions
/kind task
Fixes #
```other operator
The images built by the OpenStack provider-extension are now multiarch-images, supporting x86_64 and arm64
```
=> Also build and publish arm64 images

.ci/testruns/default/templates/testrun.yaml, .gitignore, .test-defs/backupbucket-test.yaml, Makefile, test/integration/backupbucket/backupbucket_suite_test.go, test/integration/backupbucket/backupbucket_test.go, test/integration/backupbucket/helper_test.go
/area testing
/kind test
adds integration test for backupbuckets
Fixes #
=> Add backupbucket integration test

pkg/controller/bastion/actuator.go, pkg/controller/bastion/actuator_delete.go, pkg/controller/bastion/actuator_reconcile.go, pkg/controller/bastion/bastion_suite_test.go, pkg/controller/bastion/options.go, pkg/controller/bastion/resourcesdefine.go, test/integration/bastion/bastion_test.go
/area quality
Separate bastion reconcile and delete options
Fixes #
```other developer
Separate bastion reconcile and delete options
```
=> Separate bastion reconcile and delete options

.github/workflows/non-release.yaml
/area TODO
/kind TODO
Fixes #
```other operator
NONE
```
=> add fixes for gha

.github/workflows/non-release.yaml
/area quality
Fixes #
```other operator
NONE
```
=> Add Github actions build on workflow_dispatch

.github/workflows/non-release.yaml, .github/workflows/pullrequest-trust-helper.yaml
Sync current GHA behaviour with other provider-ext's
=> Sync GHAs with other providers

.github/workflows/build.yaml, .github/workflows/integration-tests.yaml, .github/workflows/release.yaml
/area TODO
/kind TODO
Fixes #
```other operator
NONE
```
=> integration test gha
